/**
 * @module features/prescription-scanner/types
 * Shared TypeScript types for the PrescriptionScanner module.
 */

// ─── Primary result returned by PrescriptionScanner.scan() ─────────────────

export interface ScanResult {
  /** Local file URI of the scanned image, or null if no image was captured. */
  imageUri: string | null;
  /** Raw text extracted via OCR. Empty string when OCR is unavailable. */
  extractedText: string;
  /** Confidence that the scanned image is a valid medical prescription (0.0 - 1.0). */
  confidence: number;
  /** Categorized level of confidence based on thresholds. */
  level: 'HIGH' | 'MEDIUM' | 'LOW';
  /** True if the image is likely a prescription (HIGH confidence). */
  likelyPrescription: boolean;
  /** True if there is a sufficient mass of text to assume a document is present. */
  documentDetected: boolean;
  /** Prescription-related keywords that were detected in the OCR text. */
  matchedKeywords: string[];
  /** Optional warning message generated by the validation engine. */
  warningMessage?: string;
  /** True when the user cancelled the scanner without capturing an image. */
  cancelled: boolean;
}

// ─── OCR layer ──────────────────────────────────────────────────────────────

export interface OcrResult {
  /** Full text block recognised from the image. */
  text: string;
  /**
   * Raw confidence returned by the OCR engine (0.0 – 1.0).
   * 0 when OCR is unavailable or the image contained no text.
   */
  confidence: number;
}

// ─── Validation layer ───────────────────────────────────────────────────────

export interface ValidationResult {
  confidence: number;
  level: 'HIGH' | 'MEDIUM' | 'LOW';
  likelyPrescription: boolean;
  documentDetected: boolean;
  matchedKeywords: string[];
  extractedText: string;
  warningMessage?: string;
}


// ─── Scanner layer ──────────────────────────────────────────────────────────

export interface RawScanOutput {
  imageUri: string | null;
  cancelled: boolean;
}
