import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  // PreviewDisplay
  displayRoot: {
    flex: 1,
    position: "relative",
  },
  displayCard: {
    flex: 1,
    borderRadius: exactScale(6),
    overflow: "hidden",
    shadowColor: "#919EAB33",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 1,
    elevation: 0,
    borderWidth: 1,
    borderColor: "#919EAB33",
    backgroundColor: "#F9FAFB",
  },
  pdfContainer: {
    backgroundColor: "#F9FAFB",
  },
  animatedViewCenter: {
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  navArrowBtn: {
    position: "absolute",
    top: "50%",
    marginTop: exactScale(-24),
    width: exactScale(48),
    height: exactScale(48),
    borderRadius: exactScale(24),
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#919EAB33",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20,
    elevation: 8,
    shadowColor: "#919EAB33",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
  },
  navArrowBtnLeft: {
    left: exactScale(-20),
  },
  navArrowBtnRight: {
    right: exactScale(-20),
  },

  // PreviewThumbnails
  thumbnailsRoot: {
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#919EAB33",
    shadowColor: "#919EAB33",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
  },
  thumbnailsScrollContent: {
    paddingHorizontal: exactScale(24),
    paddingVertical: exactScale(20),
    gap: exactScale(12),
  },
  addPhotoBtn: {
    width: exactScale(82),
    height: exactScale(82),
    borderRadius: exactScale(14),
    borderWidth: 1,
    borderColor: "#919EAB33",
    backgroundColor: "#FCFDFF",
    alignItems: "center",
    justifyContent: "center",
  },
  thumbBox: {
    width: exactScale(82),
    height: exactScale(82),
    borderRadius: exactScale(8),
    overflow: "hidden",
    backgroundColor: "#F9FAFB",
  },
  thumbImage: {
    width: "100%",
    height: "100%",
  },
  pdfThumbBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  pdfThumbText: {
    fontSize: moderateScale(8),
    fontWeight: "700",
    color: "#1A1C1E",
    marginTop: exactScale(4),
  },
  removeThumbBtn: {
    position: "absolute",
    top: exactScale(6),
    right: exactScale(6),
    backgroundColor: "#FFFFFF",
    borderRadius: exactScale(10),
    width: exactScale(20),
    height: exactScale(20),
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#919EAB33",
    zIndex: 30,
    elevation: 2,
  },
  statusBadgeSuccess: {
    position: "absolute",
    bottom: exactScale(4),
    left: exactScale(4),
    right: exactScale(4),
    backgroundColor: "#0F7635",
    borderRadius: exactScale(6),
    alignItems: "center",
    paddingVertical: exactScale(2),
  },
  statusBadgeError: {
    position: "absolute",
    bottom: exactScale(4),
    left: exactScale(4),
    right: exactScale(4),
    backgroundColor: "#E02D5B",
    borderRadius: exactScale(6),
    alignItems: "center",
    paddingVertical: exactScale(2),
  },
  statusBadgeUploading: {
    position: "absolute",
    bottom: exactScale(4),
    left: exactScale(4),
    right: exactScale(4),
    backgroundColor: "rgba(26, 28, 30, 0.8)",
    borderRadius: exactScale(6),
    alignItems: "center",
    paddingVertical: exactScale(2),
  },
  statusBadgeWaiting: {
    position: "absolute",
    bottom: exactScale(4),
    left: exactScale(4),
    right: exactScale(4),
    backgroundColor: "rgba(106, 106, 106, 0.8)",
    borderRadius: exactScale(6),
    alignItems: "center",
    paddingVertical: exactScale(2),
  },
  statusBadgeText: {
    color: "#FFFFFF",
    fontSize: moderateScale(9),
    fontWeight: "600",
  },
  footerTitle: {
    fontSize: moderateScale(14),
    fontWeight: "500",
    color: "#1A1C1E",
    marginBottom: exactScale(8),
  },
  proceedBtnFull: {
    width: "100%",
  },

  // UploadProgressPanel
  progressPanel: {
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#919EAB1A",
    paddingHorizontal: exactScale(24),
    paddingTop: exactScale(16),
    paddingBottom: exactScale(4),
  },
  progressHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  progressTitle: {
    fontSize: moderateScale(14),
    fontWeight: "600",
    color: "#1A1C1E",
  },
  progressPercent: {
    fontSize: moderateScale(14),
    fontWeight: "600",
    color: "#0F7635",
  },
  progressSubtext: {
    fontSize: moderateScale(12),
    color: "#6A6A6A",
    fontWeight: "500",
    marginTop: exactScale(4),
  },
  progressBarTrack: {
    height: exactScale(6),
    borderRadius: exactScale(999),
    backgroundColor: "#E5E7EB",
    overflow: "hidden",
    marginTop: exactScale(10),
  },
  progressBarFill: {
    height: exactScale(6),
    borderRadius: exactScale(999),
    backgroundColor: "#0F7635",
  },
  progressKeepOpenText: {
    fontSize: moderateScale(11),
    color: "#6A6A6A",
    fontWeight: "500",
    marginTop: exactScale(8),
  },
});
