import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: exactScale(28),
  },
  emptyHero: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: exactScale(32),
    paddingTop: exactScale(24),
    paddingBottom: exactScale(58),
  },
  emptyLottie: {
    width: exactScale(140),
    height: exactScale(140),
  },
  emptyTitle: {
    fontSize: moderateScale(17),
    lineHeight: moderateScale(22),
    fontFamily: "Inter-700Bold",
    color: "#111111",
    marginTop: exactScale(8),
  },
  browseBtn: {
    backgroundColor: "#0F7635",
    alignItems: "center",
    justifyContent: "center",
    width: exactScale(152),
    height: exactScale(50),
    borderRadius: exactScale(12),
    marginTop: exactScale(20),
  },
  browseBtnText: {
    fontSize: moderateScale(16),
    lineHeight: moderateScale(20),
    fontFamily: "Inter-600SemiBold",
    color: "#FFFFFF",
  },
  sectionTitle: {
    paddingHorizontal: exactScale(16),
    fontSize: moderateScale(16),
    lineHeight: moderateScale(21),
    fontFamily: "Inter-700Bold",
    color: "#222222",
    marginBottom: exactScale(10),
  },
  horizontalScrollContent: {
    paddingHorizontal: exactScale(16),
    paddingTop: 0,
    paddingBottom: exactScale(16),
  },
  productCard: {
    width: exactScale(167),
    marginRight: exactScale(10),
  },
  imageCard: {
    height: exactScale(163),
    borderRadius: exactScale(13),
    borderWidth: 1,
    borderColor: "#DDE1E8",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  productImg: {
    width: "82%",
    height: "82%",
  },
  discountBadge: {
    position: "absolute",
    top: exactScale(12),
    left: exactScale(11),
    zIndex: 10,
    borderRadius: exactScale(4),
    paddingHorizontal: exactScale(8),
    paddingVertical: exactScale(5),
    backgroundColor: "#008FA3",
    overflow: "hidden",
  },
  discountText: {
    fontSize: moderateScale(13),
    lineHeight: moderateScale(16),
    fontWeight: "700",
    color: "#FFFFFF",
  },
  infoContainer: {
    marginTop: exactScale(14),
  },
  productName: {
    minHeight: moderateScale(42),
    fontSize: moderateScale(15),
    fontWeight: "500",
    color: "#252525",
    lineHeight: moderateScale(21),
  },
  productBrand: {
    fontSize: moderateScale(13),
    lineHeight: moderateScale(18),
    fontWeight: "700",
    color: "#009B8D",
    marginTop: exactScale(6),
  },
  productPack: {
    fontSize: moderateScale(12),
    lineHeight: moderateScale(17),
    fontWeight: "500",
    color: "#6A6A6A",
    marginTop: exactScale(2),
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "baseline",
    minHeight: moderateScale(23),
    marginTop: exactScale(8),
  },
  priceText: {
    fontSize: moderateScale(17),
    lineHeight: moderateScale(22),
    fontWeight: "700",
    color: "#111827",
  },
  originalPriceText: {
    fontSize: moderateScale(13),
    lineHeight: moderateScale(18),
    fontWeight: "400",
    color: "#777777",
    textDecorationLine: "line-through",
    marginLeft: exactScale(7),
  },
  addBtn: {
    height: exactScale(39),
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#0F7635",
    borderRadius: exactScale(12),
    alignItems: "center",
    justifyContent: "center",
    marginTop: exactScale(10),
  },
  addBtnText: {
    fontSize: moderateScale(14),
    lineHeight: moderateScale(18),
    fontWeight: "700",
    color: "#0F7635",
  },
});
