import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  appliedContainer: {
    marginHorizontal: exactScale(16),
    marginTop: exactScale(12),
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#919EAB33",
    borderRadius: exactScale(12),
    paddingHorizontal: exactScale(16),
    paddingVertical: exactScale(12),
  },
  appliedRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  appliedLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: exactScale(8),
    flex: 1,
    marginRight: exactScale(8),
  },
  couponIconSmall: {
    width: exactScale(22),
    height: exactScale(22),
  },
  codeBadge: {
    backgroundColor: "#E8F5E9",
    paddingHorizontal: exactScale(8),
    paddingVertical: exactScale(4),
    borderRadius: exactScale(4),
    flexShrink: 0,
    position: "relative",
    overflow: "hidden",
  },
  codeBadgeText: {
    fontSize: moderateScale(13),
    fontFamily: "Inter-700Bold",
    fontWeight: "700",
    color: "#0F7635",
  },
  savedText: {
    fontSize: moderateScale(13),
    fontFamily: "Inter-500Medium",
    color: "#0F7635",
    flexShrink: 1,
  },
  removeBtnText: {
    fontSize: moderateScale(13),
    fontFamily: "Inter-600SemiBold",
    color: "#E16D09",
  },
  skeletonWrap: {
    marginHorizontal: exactScale(16),
    marginTop: exactScale(12),
  },
  simpleCard: {
    marginHorizontal: exactScale(16),
    marginTop: exactScale(12),
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#919EAB33",
    borderRadius: exactScale(12),
    paddingHorizontal: exactScale(16),
    paddingVertical: exactScale(12),
  },
  simpleCardTouchable: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  simpleCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: exactScale(12),
  },
  simpleCardTitle: {
    fontSize: moderateScale(14),
    fontFamily: "Inter-600SemiBold",
    color: "#222222",
  },
  fullCard: {
    marginHorizontal: exactScale(16),
    marginTop: exactScale(12),
    borderRadius: exactScale(16),
    borderWidth: 1,
    borderColor: "#BFE3FF",
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
  },
  fullCardTop: {
    backgroundColor: "#EAF6FF",
    paddingHorizontal: exactScale(16),
    paddingTop: exactScale(16),
    paddingBottom: exactScale(16),
  },
  fullCardHeading: {
    fontSize: moderateScale(15),
    fontWeight: "700",
    color: "#1A1C1E",
    marginBottom: exactScale(10),
  },
  fullCardRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  fullCardIconBox: {
    width: exactScale(44),
    height: exactScale(44),
    borderRadius: exactScale(10),
    backgroundColor: "#E1F2FF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: exactScale(12),
    borderWidth: 1,
    borderColor: "#BFE3FF",
  },
  fullCardIcon: {
    width: exactScale(24),
    height: exactScale(24),
  },
  fullCardBody: {
    flex: 1,
    marginRight: exactScale(8),
  },
  fullCardTitle: {
    fontSize: moderateScale(14),
    fontWeight: "700",
    color: "#1A1C1E",
    lineHeight: moderateScale(18),
  },
  fullCardUpsellText: {
    fontSize: moderateScale(12),
    fontWeight: "600",
    color: "#FF8A00",
    marginTop: exactScale(3),
  },
  applyActionBtn: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderRadius: exactScale(6),
    width: exactScale(72),
    height: exactScale(42),
    padding: exactScale(8),
    alignItems: "center",
    justifyContent: "center",
  },
  applyActionBtnText: {
    fontSize: moderateScale(13),
    fontWeight: "700",
  },
  cardDashedDivider: {
    height: 1,
    borderBottomWidth: 1,
    borderBottomColor: "#E3EFFD",
    borderStyle: "dashed",
    width: "100%",
  },
  viewAllRow: {
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: exactScale(16),
    paddingVertical: exactScale(14),
  },
  viewAllText: {
    fontSize: moderateScale(14),
    fontWeight: "500",
    color: "#6A6A6A",
  },
});
