import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  // ─── KnowYourMedicine ────────────────────────────────────────────────────────
  kymGradient: {
    padding: exactScale(16),
  },
  kymTitle: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#6B2A75",
    fontSize: moderateScale(17),
    marginBottom: exactScale(16),
    paddingLeft: exactScale(4),
  },
  kymCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: exactScale(12),
    paddingHorizontal: exactScale(20),
    paddingVertical: exactScale(24),
    marginBottom: exactScale(28),
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  kymRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: exactScale(24),
  },
  kymRowLast: {
    flexDirection: "row",
    alignItems: "center",
  },
  kymIconBox: {
    borderRadius: exactScale(6),
    alignItems: "center",
    justifyContent: "center",
    marginRight: exactScale(16),
    width: exactScale(48),
    height: exactScale(48),
  },
  kymChemicalBox: {
    backgroundColor: "#F1F7FF",
  },
  kymMedicineBox: {
    backgroundColor: "#F4F1FF",
  },
  kymDeliveryBox: {
    backgroundColor: "#F1F7FF",
  },
  kymIconImage: {
    width: exactScale(24),
    height: exactScale(24),
  },
  kymTextCol: {
    flex: 1,
  },
  kymLabel: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#111827",
    marginBottom: exactScale(4),
    fontSize: moderateScale(15),
  },
  kymValueTeal: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#009989",
    fontSize: moderateScale(14),
  },
  kymValueGray: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#6B7280",
    fontSize: moderateScale(14),
  },

  // ─── LogisticsBar ────────────────────────────────────────────────────────────
  logisticsRoot: {
    marginHorizontal: exactScale(16),
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#919EAB33",
    borderRadius: exactScale(12),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: exactScale(16),
    paddingVertical: exactScale(8),
    marginBottom: exactScale(24),
  },
  logisticsLeft: {
    flexDirection: "row",
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: "#F3F4F6",
    paddingRight: exactScale(16),
    flex: 1,
    minWidth: 0,
  },
  logisticsText: {
    fontFamily: "Inter-Regular",
    color: "#111827",
    marginLeft: exactScale(8),
    fontSize: moderateScale(12),
  },
  logisticsTimeBold: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#111827",
  },
  logisticsRight: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: exactScale(16),
    flexShrink: 0,
    minHeight: exactScale(44),
    justifyContent: "center",
  },
  logisticsLocationLabel: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#111827",
    marginHorizontal: exactScale(8),
    maxWidth: exactScale(70),
    fontSize: moderateScale(12),
  },
  logisticsChangeText: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#0F7635",
    fontSize: moderateScale(14),
    flexShrink: 0,
  },

  // ─── TrustBadge ──────────────────────────────────────────────────────────────
  trustBadgeRoot: {
    paddingTop: exactScale(24),
    paddingBottom: exactScale(24),
  },
  trustBadgeInner: {
    paddingHorizontal: exactScale(16),
    marginBottom: exactScale(24),
  },
  trustBadgeTitle: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#111827",
    marginBottom: exactScale(16),
    textAlign: "center",
    fontSize: moderateScale(14),
  },
  trustBadgeCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: exactScale(16),
    padding: exactScale(20),
    borderWidth: 1,
    borderColor: "#919EAB33",
  },
  trustBadgeFieldLabel: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#6B7280",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: exactScale(8),
    textAlign: "center",
    fontSize: moderateScale(12),
  },
  trustBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  trustBadgeSearchedText: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#111827",
    flex: 1,
    marginRight: exactScale(8),
    fontSize: moderateScale(14),
  },
  trustBadgeRecommendedText: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#0F7635",
    flex: 1,
    textAlign: "right",
    fontSize: moderateScale(14),
  },
  trustBadgeMatchBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: exactScale(10),
    borderRadius: exactScale(6),
    backgroundColor: "#F1FFF6",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#0F7635",
  },
  trustBadgeMatchText: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#0F7635",
    marginLeft: exactScale(6),
    fontSize: moderateScale(14),
  },
  trustBadgeDashedDivider: {
    borderTopWidth: 1,
    borderColor: "#E5E7EB",
    borderStyle: "dashed",
    marginVertical: exactScale(16),
  },

  // ─── NoSubstituteBanner ──────────────────────────────────────────────────────
  noSubRoot: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: exactScale(20),
    paddingTop: exactScale(16),
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    shadowColor: "#919EAB33",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 12,
  },
  noSubTopRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: exactScale(16),
  },
  noSubTitle: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#111827",
    marginLeft: exactScale(10),
    fontSize: moderateScale(16),
  },
  noSubBtn: {
    borderRadius: exactScale(12),
    height: exactScale(48),
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  noSubBtnText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#FFFFFF",
    textAlign: "center",
    fontSize: moderateScale(15),
  },

  // ─── SaltCompositionBanner ───────────────────────────────────────────────────
  saltRoot: {
    borderRadius: exactScale(12),
    overflow: "hidden",
    paddingHorizontal: exactScale(16),
    borderBottomWidth: 1,
    borderBottomColor: "#919EAB33",
    borderStyle: "dashed",
    backgroundColor: "#14835A",
    minHeight: exactScale(40),
    marginHorizontal: exactScale(16),
    marginVertical: exactScale(16),
  },
  saltBgImage: {
    ...StyleSheet.absoluteFill,
    width: "100%",
    height: "100%",
  },
  saltContentRow: {
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
    zIndex: 10,
    width: "100%",
    minHeight: exactScale(46),
    paddingVertical: exactScale(6),
  },
  saltBeakerWrap: {
    alignItems: "center",
    justifyContent: "center",
    marginRight: exactScale(8),
  },
  saltBeakerAnimation: {
    width: exactScale(56),
    height: exactScale(56),
  },
  saltTextCol: {
    flex: 1,
  },
  saltSubHeading: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#FFFFFF",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: exactScale(2),
    fontSize: moderateScale(10),
  },
  saltCompositionText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#FFFFFF",
    lineHeight: moderateScale(20),
    fontSize: moderateScale(15),
  },
  saltChevronBtn: {
    width: exactScale(28),
    height: exactScale(28),
    borderRadius: exactScale(14),
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: exactScale(8),
  },

  // ─── MoreAboutTabs & Content ─────────────────────────────────────────────────
  tabsContainer: {
    marginHorizontal: exactScale(16),
    overflow: "hidden",
    borderTopLeftRadius: exactScale(12),
    borderTopRightRadius: exactScale(12),
    backgroundColor: "#FFFFFF",
    zIndex: 21,
  },
  tabsScrollView: {
    backgroundColor: "#F4F7FC",
  },
  tabsScrollContent: {
    paddingTop: exactScale(14),
  },
  tabTouchable: {
    marginRight: exactScale(24),
    paddingBottom: exactScale(12),
  },
  tabLabelActive: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#0F7635",
    fontSize: moderateScale(14),
  },
  tabLabelInactive: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#6B7280",
    fontSize: moderateScale(14),
  },
  tabIndicator: {
    position: "absolute",
    bottom: 0,
    height: exactScale(3),
    borderRadius: exactScale(999),
    backgroundColor: "#0F7635",
  },
  moreAboutContentCard: {
    marginHorizontal: exactScale(8),
    marginBottom: exactScale(16),
    overflow: "hidden",
    borderRadius: exactScale(12),
    backgroundColor: "#FFFFFF",
  },
  moreAboutContentInner: {
    paddingHorizontal: exactScale(8),
    paddingBottom: exactScale(20),
    paddingTop: exactScale(16),
  },
  moreAboutSectionTitle: {
    marginBottom: exactScale(12),
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#111827",
    fontSize: moderateScale(15),
    lineHeight: moderateScale(20),
  },
  moreAboutHeading: {
    marginHorizontal: exactScale(16),
    marginBottom: exactScale(12),
    marginTop: exactScale(24),
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#111827",
    fontSize: moderateScale(16),
  },
  viewMoreToggleBtn: {
    marginTop: exactScale(12),
    alignSelf: "flex-start",
    paddingHorizontal: exactScale(8),
    paddingVertical: exactScale(4),
  },
  viewMoreToggleText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#0F7635",
    fontSize: moderateScale(13),
  },
});
