import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  outerPad: {
    paddingHorizontal: exactScale(16),
    zIndex: 10,
    marginBottom: exactScale(8),
  },
  row: {
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-between",
  },
  searchBox: {
    height: exactScale(60),
    borderRadius: exactScale(12),
    borderWidth: 1.05,
    borderColor: "#919EAB33",
    paddingLeft: exactScale(16),
    paddingRight: exactScale(16),
    shadowColor: "#919EAB0A",
    shadowOffset: { width: 0, height: exactScale(6) },
    shadowRadius: exactScale(10),
    shadowOpacity: 0.1,
    elevation: 4,
    flex: 1,
    marginRight: exactScale(12),
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  backBtn: {
    marginRight: exactScale(12),
    alignItems: "center",
    justifyContent: "center",
  },
  inputWrap: {
    flex: 1,
    justifyContent: "center",
  },
  inputText: {
    fontFamily: "Inter-Regular",
    fontWeight: "400",
    color: "#222222",
    padding: 0,
    margin: 0,
    height: exactScale(28),
    letterSpacing: 0,
    includeFontPadding: false,
    fontSize: moderateScale(14),
    lineHeight: moderateScale(16),
  },
  clearBtn: {
    marginLeft: exactScale(8),
  },
  queryText: {
    flex: 1,
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#222222",
    fontSize: moderateScale(15),
  },
  uploadBtn: {
    borderLeftWidth: 1,
    borderLeftColor: "#919EAB33",
    paddingLeft: exactScale(12),
    marginLeft: exactScale(4),
  },
  cartBtn: {
    height: exactScale(60),
    width: exactScale(60),
    borderWidth: 1.05,
    borderColor: "#919EAB33",
    shadowColor: "#919EAB0A",
    shadowOffset: { width: 0, height: exactScale(6) },
    shadowRadius: exactScale(10),
    shadowOpacity: 0.1,
    elevation: 4,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: exactScale(12),
    position: "relative",
  },
  cartBadge: {
    position: "absolute",
    top: -exactScale(4),
    right: -exactScale(4),
    minWidth: exactScale(20),
    height: exactScale(20),
    paddingHorizontal: exactScale(4),
    borderRadius: exactScale(10),
    backgroundColor: "#C22923",
    alignItems: "center",
    justifyContent: "center",
  },
  cartBadgeText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#FFFFFF",
    lineHeight: exactScale(14),
    fontSize: moderateScale(11),
  },
});
