plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.codeneptune.caresure'
version = '1.0.0'

android {
  namespace "expo.modules.nativenotifications"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  // NotificationCompat / NotificationManagerCompat / RemoteViews-adjacent APIs.
  implementation 'androidx.core:core:1.17.0'
}
