import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const COUNTER_WIDTH = exactScale(90);
export const COUNTER_BTN_W = exactScale(36);

export const styles = StyleSheet.create({
  cardRoot: {
    width: "100%",
    borderRadius: exactScale(12),
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    marginBottom: exactScale(20),
    borderWidth: 1,
    borderColor: "#919EAB33",
  },
  splitRow: {
    flexDirection: "row",
    width: "100%",
  },
  leftSide: {
    flex: 1,
    padding: exactScale(16),
  },
  rightSide: {
    flex: 1,
    padding: exactScale(16),
    backgroundColor: "#FFFDEB",
  },
  titleCol: {
    marginBottom: exactScale(24),
  },
  name: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#111827",
    marginBottom: exactScale(4),
    fontSize: moderateScale(14),
    lineHeight: moderateScale(22),
    letterSpacing: -0.2,
  },
  desc: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#6B7280",
    marginTop: exactScale(2),
    fontSize: moderateScale(12),
  },
  descManufacturer: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#009989",
    marginTop: exactScale(2),
    fontSize: moderateScale(12),
  },
  priceCol: {
    marginTop: "auto",
  },
  searchedPrice: {
    fontFamily: "Inter-ExtraBold",
    fontWeight: "800",
    color: "#111827",
    marginBottom: exactScale(6),
    fontSize: moderateScale(18),
    lineHeight: moderateScale(18),
    letterSpacing: -0.2,
  },
  searchedStatus: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#FF383C",
    marginTop: exactScale(4),
    fontSize: moderateScale(12),
    lineHeight: moderateScale(12),
  },
  recPriceRow: {
    flexDirection: "row",
    alignItems: "baseline",
    flexWrap: "wrap",
    columnGap: exactScale(8),
    rowGap: moderateScale(2),
    marginBottom: exactScale(6),
  },
  recPrice: {
    fontFamily: "Inter-ExtraBold",
    fontWeight: "800",
    color: "#111827",
    fontSize: moderateScale(18),
    lineHeight: moderateScale(20),
    letterSpacing: -0.2,
  },
  recMrp: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#6B7280",
    textDecorationLine: "line-through",
    fontSize: moderateScale(14),
    lineHeight: moderateScale(16),
  },
  savingsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: exactScale(2),
  },
  sellIcon: {
    width: exactScale(15),
    height: exactScale(15),
    top: exactScale(1.5),
    left: exactScale(1.5),
  },
  savingsText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#0F7635",
    marginLeft: exactScale(6),
    marginTop: exactScale(4),
    fontSize: moderateScale(12),
    lineHeight: moderateScale(12),
    letterSpacing: -0.2,
  },
  dividerLine: {
    height: 1,
    width: "100%",
    backgroundColor: "#EAEAEA",
  },
  bottomSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: exactScale(16),
    paddingVertical: exactScale(14),
    backgroundColor: "#FFFFFF",
  },
  sameCompRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  sameCompText: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#0F7635",
    marginLeft: exactScale(8),
    fontSize: moderateScale(14),
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  addBtn: {
    minWidth: exactScale(78),
    height: exactScale(35),
    alignSelf: "flex-start",
    borderRadius: exactScale(6),
    borderWidth: 1,
    borderColor: "#0F7635",
    paddingVertical: exactScale(8),
    paddingHorizontal: exactScale(24),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  addText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#0F7635",
    fontSize: moderateScale(14),
  },
  wrapActive: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: exactScale(10),
    overflow: "hidden",
    width: COUNTER_WIDTH,
    height: exactScale(35),
    backgroundColor: "#0F7635",
  },
  btn: {
    width: COUNTER_BTN_W,
    paddingVertical: exactScale(6),
    alignItems: "center",
    justifyContent: "center",
  },
  plusMinus: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#FFFFFF",
    fontSize: moderateScale(20),
    lineHeight: moderateScale(20),
  },
  countContainer: {
    flex: 1,
    paddingVertical: exactScale(9),
    alignItems: "center",
    justifyContent: "center",
  },
  countText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#FFFFFF",
    textAlign: "center",
    fontSize: moderateScale(14),
  },
});
