import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  cardRoot: {
    width: "100%",
    borderRadius: exactScale(16),
    overflow: "hidden",
    marginBottom: exactScale(16),
    borderWidth: 1,
    borderColor: "#919EAB33",
    padding: 0,
    minHeight: 0,
  },
  topSection: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: exactScale(16),
    gap: exactScale(12),
    backgroundColor: "#FBFFF2",
  },
  imgBox: {
    width: exactScale(78),
    height: exactScale(78),
    borderRadius: exactScale(12),
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  imgInner: {
    width: exactScale(64),
    height: exactScale(64),
  },
  infoCol: {
    flex: 1,
    justifyContent: "flex-start",
  },
  name: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#111827",
    fontSize: moderateScale(14),
    lineHeight: moderateScale(22),
  },
  desc: {
    fontFamily: "Inter-Regular",
    fontWeight: "400",
    color: "#6B7280",
    marginTop: exactScale(2),
    fontSize: moderateScale(12),
  },
  descManufacturer: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#009989",
    marginTop: exactScale(2),
    fontSize: moderateScale(12),
  },
  divider: {
    height: 1,
    backgroundColor: "#E5E7EB",
  },
  bottomSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: exactScale(16),
    backgroundColor: "#FFFFFF",
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    flex: 1,
    marginRight: exactScale(8),
    rowGap: moderateScale(5),
  },
  priceBaseRow: {
    flexDirection: "row",
    alignItems: "baseline",
    columnGap: exactScale(6),
    flexShrink: 0,
  },
  price: {
    fontFamily: "Inter-ExtraBold",
    fontWeight: "800",
    color: "#111827",
    fontSize: moderateScale(18),
    lineHeight: moderateScale(18),
  },
  mrp: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#6B7280",
    textDecorationLine: "line-through",
    fontSize: moderateScale(14),
    lineHeight: moderateScale(14),
  },
  savingsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: exactScale(8),
    flexShrink: 0,
  },
  sellIcon: {
    width: exactScale(15),
    height: exactScale(15),
    top: exactScale(1.5),
    left: exactScale(1.5),
  },
  savingsText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#0F7635",
    marginLeft: exactScale(6),
    fontSize: moderateScale(12),
    lineHeight: moderateScale(16),
    letterSpacing: -0.2,
  },
  addBtn: {
    minWidth: exactScale(78),
    height: exactScale(35),
    alignSelf: "flex-start",
    borderRadius: exactScale(6),
    borderWidth: 1,
    borderColor: "#0F7635",
    paddingVertical: exactScale(8),
    paddingHorizontal: exactScale(24),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  addText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#0F7635",
    fontSize: moderateScale(14),
  },
  wrapActive: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: exactScale(10),
    overflow: "hidden",
    width: exactScale(90),
    height: exactScale(35),
    backgroundColor: "#0F7635",
  },
  btn: {
    width: exactScale(36),
    paddingVertical: exactScale(6),
    alignItems: "center",
    justifyContent: "center",
  },
  plusMinus: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#FFFFFF",
    fontSize: moderateScale(20),
    lineHeight: moderateScale(20),
  },
  countContainer: {
    flex: 1,
    paddingVertical: exactScale(9),
    alignItems: "center",
    justifyContent: "center",
  },
  countText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#FFFFFF",
    textAlign: "center",
    fontSize: moderateScale(14),
  },
});
