import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';

export const styles = StyleSheet.create({
    badge:           { fontSize: moderateScale(11, 0.08) },
    name: {
        fontWeight: '500',
        fontSize: moderateScale(14, 0.08),
        lineHeight: moderateScale(20, 0.08),
        verticalAlign: 'middle',
        letterSpacing: 0,
    },
    description: {
        fontWeight: '400',
        fontSize: 12,
        lineHeight: 18,
        letterSpacing: 0,
        verticalAlign: 'middle',
        color: '#6A6A6A',
    },
    price: {
        fontWeight: '700',
        fontSize: 16,
        lineHeight: 22.5,
        letterSpacing: 0,
        verticalAlign: 'middle',
        color: '#0F172A',
    },
    mrp: {
        fontWeight: '400',
        fontSize: 12,
        lineHeight: 18,
        letterSpacing: 0,
        verticalAlign: 'middle',
        textDecorationLine: 'line-through',
        color: '#6A6A6A',
    },
    addBtn: {
        fontWeight: '600',
        fontSize: 14,
        lineHeight: 16.84,
        letterSpacing: 0,
        verticalAlign: 'middle',
    },
    counter:         { fontSize: moderateScale(20, 0.08) },
    counterVal:      { fontSize: moderateScale(14, 0.08) },
    sectionTitle:    { fontSize: moderateScale(16, 0.08) },
    sectionSubtitle: { fontSize: moderateScale(22, 0.08), lineHeight: moderateScale(30, 0.08) },
    cartBtn: {
        width: 137,
        height: 40,
        borderRadius: 6,
        borderWidth: 1,
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        opacity: 1,
        paddingTop: 8.64,
        paddingRight: 13.82,
        paddingBottom: 8.64,
        paddingLeft: 13.82,
    },
    cartBtnActive: {
        width: 137,
        height: 38,
        borderRadius: 6,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        opacity: 1,
    },
});
