import { StyleSheet } from 'react-native';
import { exactScale } from "@/src/utils/exactScale";

export const styles = StyleSheet.create({
    badge:           { fontSize: exactScale(11) },
    name: {
        fontWeight: '500',
        fontSize: exactScale(14),
        lineHeight: exactScale(20),
        verticalAlign: 'middle',
        letterSpacing: 0,
    },
    description: {
        fontWeight: '400',
        fontSize: 12,
        lineHeight: 18,
        letterSpacing: 0,
        verticalAlign: 'middle',
        color: '#6A6A6A',
    },
    price: {
        fontWeight: '700',
        fontSize: 16,
        lineHeight: 22.5,
        letterSpacing: 0,
        verticalAlign: 'middle',
        color: '#0F172A',
    },
    mrp: {
        fontWeight: '400',
        fontSize: 12,
        lineHeight: 18,
        letterSpacing: 0,
        verticalAlign: 'middle',
        textDecorationLine: 'line-through',
        color: '#6A6A6A',
    },
    addBtn: {
        fontWeight: '600',
        fontSize: 14,
        lineHeight: 16.84,
        letterSpacing: 0,
        verticalAlign: 'middle',
    },
    counter:         { fontSize: exactScale(20) },
    counterVal:      { fontSize: exactScale(14) },
    sectionTitle:    { fontSize: exactScale(16) },
    sectionSubtitle: { fontSize: exactScale(22), lineHeight: exactScale(30) },
    cartBtn: {
        width: 137,
        height: 40,
        borderRadius: 6,
        borderWidth: 1,
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        opacity: 1,
        paddingTop: 8.64,
        paddingRight: 13.82,
        paddingBottom: 8.64,
        paddingLeft: 13.82,
    },
    cartBtnActive: {
        width: 137,
        height: 38,
        borderRadius: 6,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        opacity: 1,
    },
});
