import { StyleSheet } from 'react-native';
import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { typography } from "@/src/constants/typography";

export const styles = StyleSheet.create({
    badgeContainer: {
        position: 'absolute',
        top: exactScale(6),
        left: exactScale(8),
        paddingHorizontal: exactScale(6),
        paddingVertical: exactScale(4),
        borderRadius: exactScale(4),
    },
    badge:           { fontSize: moderateScale(11) },
    name: {
        fontWeight: '500',
        fontSize: typography.body.fontSize,
        lineHeight: typography.body.lineHeight,
        verticalAlign: 'middle',
        letterSpacing: 0,
    },
    description: {
        fontWeight: '400',
        fontSize: moderateScale(12),
        lineHeight: moderateScale(18),
        letterSpacing: 0,
        verticalAlign: 'middle',
        color: '#6A6A6A',
    },
    price: {
        fontWeight: '700',
        fontSize: moderateScale(16),
        lineHeight: moderateScale(22.5),
        letterSpacing: 0,
        verticalAlign: 'middle',
        color: '#0F172A',
    },
    mrp: {
        fontWeight: '400',
        fontSize: moderateScale(12),
        lineHeight: moderateScale(18),
        letterSpacing: 0,
        verticalAlign: 'middle',
        textDecorationLine: 'line-through',
        color: '#6A6A6A',
    },
    addBtn: {
        fontWeight: '600',
        fontSize: moderateScale(14),
        lineHeight: moderateScale(16.84),
        letterSpacing: 0,
        verticalAlign: 'middle',
    },
    counter:         { fontSize: moderateScale(20) },
    counterVal:      { fontSize: moderateScale(14) },
    sectionTitle:    { fontSize: moderateScale(16) },
    sectionSubtitle: { fontSize: moderateScale(22), lineHeight: moderateScale(30) },
    cartBtn: {
        width: exactScale(137),
        height: exactScale(40),
        borderRadius: exactScale(6),
        borderWidth: 1,
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        opacity: 1,
        paddingTop: exactScale(8.64),
        paddingRight: exactScale(13.82),
        paddingBottom: exactScale(8.64),
        paddingLeft: exactScale(13.82),
    },
    cartBtnActive: {
        width: exactScale(137),
        height: exactScale(38),
        borderRadius: exactScale(6),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        opacity: 1,
    },
});
