import { colors } from "@/src/constants/theme";
import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  deliverLabel: {
    fontSize: moderateScale(12),
    lineHeight: moderateScale(14),
    letterSpacing: 0.4,
    color: "#333232",
  },
  locationText: {
    fontSize: moderateScale(16),
    lineHeight: moderateScale(18),
    letterSpacing: 0,
    color: colors.text,
  },
  dropDownIcon: {
    marginLeft: exactScale(10),
    width: exactScale(10),
    height: exactScale(5),
  },
  iconBtn: {
    width: exactScale(44),
    height: exactScale(44),
    borderRadius: exactScale(9999),
    opacity: 1,
    shadowColor: "#919EAB",
    shadowOffset: { width: 0, height: exactScale(2) },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  notificationBtn: {
    width: exactScale(44),
    height: exactScale(44),
    borderRadius: exactScale(9999),
    opacity: 1,
    shadowColor: "#919EAB",
    shadowOffset: { width: 0, height: exactScale(2) },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  notificationIcon: {
    width: exactScale(24),
    height: exactScale(26),
  },
  walletIcon: {
    width: exactScale(32),
    height: exactScale(32),
    opacity: 1,
  },
  walletBadgeWrap: {
    minWidth: exactScale(54),
    minHeight: exactScale(12),
    paddingTop: exactScale(2),
    paddingRight: exactScale(9),
    paddingBottom: exactScale(2),
    paddingLeft: exactScale(9),
    borderRadius: exactScale(18),
    borderWidth: 0.5,
    borderColor: "#919EAB33",
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    opacity: 1,
  },
  walletBadgeText: {
    fontSize: moderateScale(10),
    lineHeight: moderateScale(13),
    letterSpacing: 0,
    color: colors.text,
    padding: 1,
  },
  badge: { minWidth: exactScale(18), height: exactScale(18) },
  badgeText: { fontSize: moderateScale(10) },
});
