import { colors } from "@/src/constants/theme";
import { StyleSheet } from "react-native";
import { moderateScale, scale } from "react-native-size-matters";

export const styles = StyleSheet.create({
  deliverLabel: {
    fontSize: moderateScale(12, 0.3),
    lineHeight: moderateScale(16, 0.3),
    letterSpacing: 0,
    color: "#333232",
  },
  locationText: {
    fontSize: moderateScale(16, 0.3),
    lineHeight: moderateScale(16, 0.3),
    letterSpacing: 0,
    color: colors.text,
  },
  dropDownIcon: {
    marginLeft: scale(10),
    width: moderateScale(10, 0.5),
    height: moderateScale(5, 0.5),
  },
  iconBtn: {
    width: scale(44),
    height: scale(44),
    borderRadius: 9999,
    opacity: 1,
    shadowColor: "#919EAB",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  notificationBtn: {
    width: scale(44),
    height: scale(44),
    borderRadius: 9999,
    opacity: 1,
    shadowColor: "#919EAB",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  notificationIcon: {
    width: moderateScale(24, 0.3),
    height: moderateScale(26, 0.3),
  },
  walletIcon: {
    width: moderateScale(32, 0.3),
    height: moderateScale(32, 0.3),
    opacity: 1,
  },
  walletBadgeWrap: {
    width: scale(54),
    height: scale(15),
    paddingTop: 2,
    paddingRight: 9,
    paddingBottom: 2,
    paddingLeft: 9,
    borderRadius: 18,
    borderWidth: 0.5,
    borderColor: "#919EAB33",
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    opacity: 1,
  },
  walletBadgeText: {
    fontSize: moderateScale(10, 0.2),
    lineHeight: moderateScale(10, 0.2),
    letterSpacing: 0,
    color: colors.text,
    padding: 1,
  },
  badge: { minWidth: scale(18), height: scale(18) },
  badgeText: { fontSize: moderateScale(10, 0.2) },
});
