import { colors } from "@/src/constants/theme";
import { StyleSheet } from "react-native";
import { moderateScale, scale } from "react-native-size-matters";

export const styles = StyleSheet.create({
  deliverLabel: {
    fontSize: moderateScale(12, 0.3),
    lineHeight: moderateScale(16, 0.3),
    letterSpacing: 0,
    color: "#333232",
  },
  locationText: {
    fontSize: moderateScale(16, 0.3),
    lineHeight: moderateScale(16, 0.3),
    letterSpacing: 0,
    color: colors.text,
  },
  dropDownIcon: {
    marginLeft: scale(2),
    width: moderateScale(8.6, 0.3),
    height: moderateScale(4.7, 0.3),
  },
  iconBtn: {
    width: scale(40),
    height: scale(37),
    borderRadius: 67,
    paddingTop: 6,
    paddingRight: 8,
    paddingBottom: 8,
    paddingLeft: 8,
    opacity: 1,
    shadowColor: "#919EAB",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  notificationBtn: {
    width: scale(38),
    height: scale(38),
    borderRadius: 19,
    padding: 8,
    opacity: 1,
    shadowColor: "#919EAB",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  notificationIcon: {
    width: moderateScale(15.38, 0.3),
    height: moderateScale(17, 0.3),
  },
  walletIcon: {
    width: moderateScale(44, 0.3),
    height: moderateScale(24, 0.3),
    opacity: 1,
  },
  walletBadgeWrap: {
    width: scale(48),
    height: scale(14),
    paddingTop: 2,
    paddingRight: 9,
    paddingBottom: 2,
    paddingLeft: 9,
    borderRadius: 18,
    borderWidth: 0.5,
    borderColor: "#919EAB33",
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    opacity: 1,
  },
  walletBadgeText: {
    fontSize: moderateScale(8.5, 0.2),
    lineHeight: moderateScale(8, 0.2),
    letterSpacing: 0,
    color: colors.text,
    padding: 1,
  },
  badge: { minWidth: scale(18), height: scale(18) },
  badgeText: { fontSize: moderateScale(10, 0.2) },
});
