import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';

export const styles = StyleSheet.create({
    badge:       { fontSize: moderateScale(11, 0.25) },
    name: {
        fontFamily: 'Inter-Medium',
        fontSize: moderateScale(14, 0.25),
        lineHeight: moderateScale(20, 0.25),
        verticalAlign: 'middle',
        letterSpacing: 0,
    },
    description: {
        fontFamily: 'Inter-Regular',
        fontSize: 12,
        lineHeight: 18,
        letterSpacing: 0,
        verticalAlign: 'middle',
        color: '#6A6A6A',
    },
    price: {
        fontFamily: 'Inter-Bold',
        fontSize: 16,
        lineHeight: 22.5,
        letterSpacing: 0,
        verticalAlign: 'middle',
        color: '#0F172A',
    },
    mrp: {
        fontFamily: 'Inter-Regular',
        fontSize: 12,
        lineHeight: 18,
        letterSpacing: 0,
        verticalAlign: 'middle',
        textDecorationLine: 'line-through',
        color: '#6A6A6A',
    },
    addBtn: {
        fontFamily: 'Inter-SemiBold',
        fontSize: 14,
        lineHeight: 17.4,
        letterSpacing: 0,
        verticalAlign: 'middle',
        color: '#0F7635',
    },
    counter:     { fontSize: moderateScale(20, 0.25) },
    counterVal:  { fontSize: moderateScale(14, 0.25) },
    sectionTitle: {
        fontFamily: 'Inter-SemiBold',
        fontSize: moderateScale(16, 0.25),
        lineHeight: moderateScale(14, 0.25),
        letterSpacing: 0,
        verticalAlign: 'middle',
    },
    sectionSubtitle: {
        fontFamily: 'Inter-Bold',
        fontSize: moderateScale(20, 0.25),
        lineHeight: moderateScale(30, 0.25),
        color: '#2DAAFF',
        letterSpacing: 0,
        verticalAlign: 'middle',
    },

    headerImage: {
        width: moderateScale(48, 0.25),
        height: moderateScale(48, 0.25),
        opacity: 1,
    },
    cartBtn: {
        width: 137,
        height: 40,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#0F7635',
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        opacity: 1,
        paddingTop: 8.64,
        paddingRight: 13.82,
        paddingBottom: 8.64,
        paddingLeft: 13.82,
    },
    cartBtnActive: {
        width: 137,
        height: 38,
        borderRadius: 6,
        backgroundColor: '#0F7635',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        opacity: 1,
    },
});
