import { StyleSheet } from 'react-native';
import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { CART_BUTTON_HEIGHT } from "@/src/constants/theme";
import { typography } from "@/src/constants/typography";

export const styles = StyleSheet.create({
    badge:       { fontSize: moderateScale(11) },
    name: {
        fontWeight: '500',
        fontSize: typography.body.fontSize,
        lineHeight: typography.body.lineHeight,
        verticalAlign: 'middle',
        letterSpacing: 0,
    },
    description: {
        fontWeight: '400',
        fontSize: moderateScale(12),
        lineHeight: moderateScale(18),
        letterSpacing: 0,
        verticalAlign: 'middle',
        color: '#6A6A6A',
    },
    price: {
        fontWeight: '700',
        fontSize: moderateScale(16),
        lineHeight: moderateScale(22.5),
        letterSpacing: 0,
        verticalAlign: 'middle',
        color: '#0F172A',
    },
    mrp: {
        fontWeight: '400',
        fontSize: moderateScale(12),
        lineHeight: moderateScale(18),
        letterSpacing: 0,
        verticalAlign: 'middle',
        textDecorationLine: 'line-through',
        color: '#6A6A6A',
    },
    addBtn: {
        fontWeight: '600',
        fontSize: moderateScale(14),
        lineHeight: moderateScale(17.4),
        letterSpacing: 0,
        verticalAlign: 'middle',
        color: '#0F7635',
    },
    counter:     { fontSize: moderateScale(20) },
    counterVal:  { fontSize: moderateScale(14) },
    sectionTitle: {
        fontWeight: '600',
        fontSize: moderateScale(16),
        lineHeight: moderateScale(20),
        letterSpacing: 0,
        verticalAlign: 'middle',
    },
    sectionSubtitle: {
        fontWeight: '700',
        fontSize: moderateScale(20),
        lineHeight: moderateScale(30),
        color: '#2DAAFF',
        letterSpacing: 0,
        verticalAlign: 'middle',
    },

    headerImage: {
        width: exactScale(48),
        height: exactScale(48),
        opacity: 1,
    },
    cartBtn: {
        width: exactScale(137),
        height: CART_BUTTON_HEIGHT,
        borderRadius: exactScale(6),
        borderWidth: 1,
        borderColor: '#0F7635',
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        opacity: 1,
        paddingTop: exactScale(8.64),
        paddingRight: exactScale(13.82),
        paddingBottom: exactScale(8.64),
        paddingLeft: exactScale(13.82),
    },
    cartBtnActive: {
        width: exactScale(137),
        height: CART_BUTTON_HEIGHT,
        borderRadius: exactScale(6),
        backgroundColor: '#0F7635',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        opacity: 1,
    },
});
