const { withGradleProperties } = require("expo/config-plugins");

const JVM_ARGS_KEY = "org.gradle.jvmargs";
// R8 minification (enableMinifyInReleaseBuilds) OOM'd at the template's default
// heap (~2048m) on this project's dependency graph (Firebase, ML Kit scanner,
// notifee, Reanimated, custom native modules). 4608m fixed that, but debug
// APK packaging (zipflinger, a no-isolation worker sharing this same heap)
// OOM'd at 4608m too once the 3 new local Expo modules added more
// classes/resources to merge — 6144m covers both on a 16GB dev machine.
const JVM_ARGS_VALUE =
  "-Xmx6144m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError";

/**
 * Raises the Gradle daemon's JVM heap so release-build R8 minification has
 * enough memory to complete instead of failing with OutOfMemoryError.
 *
 * `android/gradle.properties` is regenerated by prebuild, so this must live
 * as a plugin rather than a direct edit.
 */
module.exports = function withGradleJvmHeap(config) {
  return withGradleProperties(config, (cfg) => {
    const existing = cfg.modResults.find(
      (item) => item.type === "property" && item.key === JVM_ARGS_KEY,
    );
    if (existing) {
      existing.value = JVM_ARGS_VALUE;
    } else {
      cfg.modResults.push({
        type: "property",
        key: JVM_ARGS_KEY,
        value: JVM_ARGS_VALUE,
      });
    }
    return cfg;
  });
};
