const { withAndroidManifest } = require("expo/config-plugins");

const TOOLS_NS = "http://schemas.android.com/tools";

/**
 * Adds `<profileable android:shell="true" />` to the Android manifest.
 *
 * Android Studio Profiler only lists processes that are debuggable or
 * profileable. A release build is neither by default, so the app runs but never
 * shows up in the attach list. This makes release builds attachable WITHOUT
 * `android:debuggable="true"` — no runtime, optimization, or Play Store impact.
 *
 * `android/` is regenerated by prebuild, so this must live as a plugin.
 */
module.exports = function withProfileable(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    const application = manifest.application?.[0];
    if (!application) return cfg;

    // `tools:targetApi` below needs the namespace; prebuild usually declares it already.
    manifest.$ = manifest.$ ?? {};
    if (!manifest.$["xmlns:tools"]) manifest.$["xmlns:tools"] = TOOLS_NS;

    // targetApi="q" silences the lint error, since <profileable> is API 29+ and minSdk is lower.
    application.profileable = [
      { $: { "android:shell": "true", "tools:targetApi": "q" } },
    ];
    return cfg;
  });
};
