const { withGradleProperties } = require("expo/config-plugins");

const JVM_ARGS_KEY = "org.gradle.jvmargs";
// R8 minification (enableMinifyInReleaseBuilds) OOM'd at the template's default
// heap (~2048m) on this project's dependency graph (Firebase, ML Kit scanner,
// notifee, Reanimated, custom native modules). 4608m leaves headroom on a
// 16GB dev machine while giving R8 enough room to actually complete.
const JVM_ARGS_VALUE =
  "-Xmx4608m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError";

/**
 * Raises the Gradle daemon's JVM heap so release-build R8 minification has
 * enough memory to complete instead of failing with OutOfMemoryError.
 *
 * `android/gradle.properties` is regenerated by prebuild, so this must live
 * as a plugin rather than a direct edit.
 */
module.exports = function withGradleJvmHeap(config) {
  return withGradleProperties(config, (cfg) => {
    const existing = cfg.modResults.find(
      (item) => item.type === "property" && item.key === JVM_ARGS_KEY,
    );
    if (existing) {
      existing.value = JVM_ARGS_VALUE;
    } else {
      cfg.modResults.push({
        type: "property",
        key: JVM_ARGS_KEY,
        value: JVM_ARGS_VALUE,
      });
    }
    return cfg;
  });
};
