import { colors, shadows, spacing } from "@/src/theme";
import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#F5F6FB",
  },
  addPatientHeaderBtn: {
    fontSize: moderateScale(13),
    fontWeight: "700",
    color: "#0F7635",
  },
  scrollContent: {
    padding: exactScale(spacing[4]),
  },
  sectionTitle: {
    fontSize: moderateScale(14),
    fontWeight: "600",
    color: "#1A1C1E",
    marginBottom: exactScale(10),
  },
  sectionHeadingBold: {
    fontSize: moderateScale(13),
    fontWeight: "700",
    color: "#222222",
    marginBottom: exactScale(8),
  },
  dashedDivider: {
    borderTopWidth: 1.5,
    borderColor: "#E5E7EB",
    borderStyle: "dashed",
    marginVertical: exactScale(16),
  },
  rxThumbContainer: {
    flexDirection: "row",
    gap: exactScale(10),
  },
  rxAddPhotoBtn: {
    width: exactScale(72),
    height: exactScale(72),
    borderRadius: exactScale(10),
    borderWidth: 1,
    borderColor: "#919EAB33",
    backgroundColor: "#FCFDFF",
    alignItems: "center",
    justifyContent: "center",
  },
  rxThumbItemWrap: {
    position: "relative",
    width: exactScale(72),
    height: exactScale(72),
  },
  rxThumbItem: {
    width: exactScale(72),
    height: exactScale(72),
    borderRadius: exactScale(10),
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#919EAB33",
    backgroundColor: "#F9FAFB",
  },
  rxPdfThumbBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  rxPdfThumbText: {
    fontSize: moderateScale(8),
    fontWeight: "700",
    color: "#1A1C1E",
    marginTop: exactScale(2),
  },
  rxImage: {
    width: "100%",
    height: "100%",
  },
  rxRemovingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.7)",
  },
  rxRemoveBadge: {
    position: "absolute",
    top: exactScale(6),
    right: exactScale(6),
    width: exactScale(20),
    height: exactScale(20),
    borderRadius: exactScale(10),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#919EAB33",
    elevation: 2,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    zIndex: 30,
  },
  patientsRow: {
    flexDirection: "row",
    paddingRight: exactScale(4),
    gap: exactScale(8),
  },
  patientsScrollView: {
    marginBottom: exactScale(16),
  },
  noPatientsText: {
    fontSize: moderateScale(12),
    color: "#919EAB",
    paddingVertical: exactScale(8),
  },
  patientChip: {
    paddingHorizontal: exactScale(14),
    paddingVertical: exactScale(9),
    borderRadius: exactScale(6),
    borderWidth: 1,
  },
  patientChipText: {
    fontSize: moderateScale(13),
    fontWeight: "500",
  },
  phoneRowWrapper: {
    marginBottom: exactScale(16),
  },
  phoneInputBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#919EAB33",
    borderRadius: exactScale(6),
    paddingHorizontal: exactScale(14),
    backgroundColor: "#FFFFFF",
  },
  phoneCountryPrefix: {
    fontSize: moderateScale(14),
    fontWeight: "600",
    color: "#222222",
    marginRight: exactScale(4),
  },
  phonePrefixDivider: {
    width: 1,
    height: exactScale(16),
    backgroundColor: "#919EAB33",
    marginRight: exactScale(2),
  },
  contactInput: {
    paddingVertical: exactScale(spacing[4]),
    fontSize: moderateScale(14),
    flex: 1,
    fontWeight: "600",
    color: "#222222",
  },
  contactValue: {
    paddingVertical: exactScale(spacing[4]),
    fontSize: moderateScale(14),
    flex: 1,
  },
  phoneActionText: {
    fontSize: moderateScale(13),
    fontWeight: "700",
    color: "#0F7635",
  },
  phoneErrorText: {
    fontSize: moderateScale(12),
    color: "#EF4444",
    fontWeight: "500",
    marginTop: exactScale(6),
    paddingHorizontal: exactScale(4),
  },
  vitalsRow: {
    flexDirection: "row",
    marginBottom: exactScale(16),
    gap: exactScale(12),
  },
  vitalCard: {
    paddingVertical: exactScale(spacing[4]),
    paddingHorizontal: exactScale(14),
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#919EAB33",
    borderRadius: exactScale(6),
    backgroundColor: "#FFFFFF",
  },
  vitalCardText: {
    fontSize: moderateScale(14),
  },
  vitalValueBold: {
    fontWeight: "700",
    color: "#222222",
  },
  vitalUnitSubtext: {
    fontWeight: "500",
    color: "#919EAB",
  },
  genderCard: {
    paddingVertical: exactScale(spacing[4]),
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F1FFF6",
    borderWidth: 1,
    borderColor: "#0F763533",
    borderRadius: exactScale(999),
    paddingHorizontal: exactScale(24),
  },
  genderCardText: {
    marginLeft: exactScale(6),
    fontWeight: "700",
    color: "#0F7635",
    fontSize: moderateScale(13),
  },
  healthSelector: {
    paddingVertical: exactScale(spacing[4]),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#919EAB33",
    borderRadius: exactScale(6),
    paddingHorizontal: exactScale(14),
    backgroundColor: "#FFFFFF",
    marginBottom: exactScale(16),
  },
  healthSelectedContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: exactScale(10),
  },
  healthEmoji: {
    fontSize: moderateScale(20),
    lineHeight: moderateScale(24),
  },
  healthLabel: {
    fontSize: moderateScale(14),
    fontWeight: "500",
    color: "#1A1C1E",
  },
  healthPlaceholder: {
    fontSize: moderateScale(14),
    color: "#6A6A6A",
  },
  customProblemWrapper: {
    marginBottom: exactScale(16),
  },
  customProblemInput: {
    paddingVertical: exactScale(spacing[4]),
    fontSize: moderateScale(14),
    width: "100%",
    color: "#1A1C1E",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#919EAB33",
    borderRadius: exactScale(6),
    paddingHorizontal: exactScale(14),
  },
  symptomsInput: {
    minHeight: exactScale(84),
    paddingVertical: exactScale(spacing[4]),
    textAlignVertical: "top",
    fontSize: moderateScale(14),
    borderWidth: 1,
    borderColor: "#919EAB33",
    borderRadius: exactScale(6),
    paddingHorizontal: exactScale(14),
    backgroundColor: "#FFFFFF",
    color: "#1A1C1E",
  },
  footer: {
    paddingHorizontal: exactScale(spacing[4]),
    paddingTop: exactScale(spacing[4]),
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#919EAB22",
    backgroundColor: colors.white,
  },
  continueButton: {
    width: "100%",
    height: exactScale(50),
    borderRadius: exactScale(12),
    ...(shadows.md ?? {}),
  },
  continueButtonText: {
    fontSize: moderateScale(15),
  },
});
