export const typography = {
  families: {
    thin: 'Inter-Thin',
    extralight: 'Inter-ExtraLight',
    light: 'Inter-Light',
    regular: 'Inter-Regular',
    medium: 'Inter-Medium',
    semibold: 'Inter-SemiBold',
    bold: 'Inter-Bold',
    extrabold: 'Inter-ExtraBold',
    black: 'Inter-Black',
  },
  sizes: {
    display: 28,
    h1: 24,
    h2: 20,
    h3: 18,
    bodyLg: 17,
    body: 15,
    bodySm: 13,
    caption: 12,
    button: 16,
  },
  lineHeights: {
    display: 36,
    h1: 32,
    h2: 28,
    h3: 26,
    bodyLg: 24,
    body: 22,
    bodySm: 20,
    caption: 18,
    button: 22,
  },
  letterSpacings: {
    display: -0.5,
    h1: -0.3,
    button: 0.2,
  },
} as const;
