import { StyleSheet } from "react-native";
import { exactScale, moderateScale } from "@/src/utils/exactScale";

export const IMG_SIZE = exactScale(100);

export const styles = StyleSheet.create({
  root: {
    paddingHorizontal: exactScale(16),
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: exactScale(16),
  },
  titleText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#111827",
    fontSize: moderateScale(18),
  },
  viewAllText: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#0F7635",
    fontSize: moderateScale(16),
  },
  listGap: {
    gap: exactScale(16),
  },
  itemRoot: {
    backgroundColor: "#FFFFFF",
    borderRadius: exactScale(12),
    borderWidth: 1,
    borderColor: "#919EAB1A",
    padding: exactScale(12),
    marginBottom: exactScale(10),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  itemMainTouchable: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  imgBox: {
    width: IMG_SIZE,
    height: IMG_SIZE,
    backgroundColor: "#FFFFFF",
    borderRadius: exactScale(12),
    borderWidth: 1,
    borderColor: "#919EAB1A",
    marginRight: exactScale(12),
  },
  imgContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  imgInner: {
    width: exactScale(54),
    height: exactScale(54),
    position: "absolute",
  },
  badgeWrap: {
    position: "absolute",
    top: exactScale(6),
    left: exactScale(6),
    backgroundColor: "#E8F5E9",
    paddingHorizontal: exactScale(5),
    paddingVertical: exactScale(2),
    borderRadius: exactScale(4),
    zIndex: 10,
    overflow: "hidden",
  },
  badge: {
    fontFamily: "Inter-ExtraBold",
    fontWeight: "800",
    color: "#0F7635",
    fontSize: moderateScale(10),
  },
  infoCol: {
    flex: 1,
  },
  name: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    color: "#111827",
    marginBottom: exactScale(2),
    fontSize: moderateScale(14),
  },
  brand: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#6B7280",
    marginBottom: exactScale(4),
    fontSize: moderateScale(11),
  },
  description: {
    fontFamily: "Inter-Regular",
    fontWeight: "400",
    color: "#6B7280",
    marginBottom: exactScale(8),
    fontSize: moderateScale(11),
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    columnGap: exactScale(8),
  },
  price: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#111827",
    fontSize: moderateScale(16),
  },
  mrp: {
    fontFamily: "Inter-Regular",
    fontWeight: "400",
    color: "#6B7280",
    textDecorationLine: "line-through",
    fontSize: moderateScale(12),
  },
  addBtnWrap: {
    borderRadius: exactScale(8),
    backgroundColor: "#FFFFFF",
    marginLeft: exactScale(12),
    borderWidth: 1,
    borderColor: "#0F7635",
    width: exactScale(72),
    height: exactScale(36),
    alignItems: "center",
    justifyContent: "center",
  },
  addBtn: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#0F7635",
    fontSize: moderateScale(13),
  },
  cartBtnActive: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: exactScale(8),
    overflow: "hidden",
    marginLeft: exactScale(12),
    backgroundColor: "#0F7635",
    minWidth: exactScale(72),
  },
  counterBtn: {
    width: exactScale(32),
    paddingVertical: exactScale(8),
    alignItems: "center",
    justifyContent: "center",
  },
  counter: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#FFFFFF",
    lineHeight: moderateScale(20),
    fontSize: moderateScale(18),
  },
  counterValueWrap: {
    flex: 1,
    paddingVertical: exactScale(8),
    alignItems: "center",
    justifyContent: "center",
  },
  counterVal: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#FFFFFF",
    textAlign: "center",
    fontSize: moderateScale(13),
  },
});
