import { typography } from "@/src/constants/typography";
import { CART_BUTTON_HEIGHT } from "@/src/constants/theme";
import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  cardRoot: {
    backgroundColor: "#FFFFFF",
    borderRadius: exactScale(12),
    overflow: "hidden",
    borderWidth: 0.77,
    borderColor: "#919EAB33",
  },
  imageAreaTouchable: {
    paddingBottom: exactScale(4),
  },
  imageAreaInner: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: exactScale(12),
    borderTopRightRadius: exactScale(12),
    alignItems: "center",
    justifyContent: "center",
  },
  imageWrap: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  productImage: {
    width: "100%",
    height: "100%",
    position: "absolute",
  },
  badgeContainer: {
    position: "absolute",
    top: exactScale(6),
    left: exactScale(8),
    paddingHorizontal: exactScale(6),
    paddingVertical: exactScale(4),
    borderRadius: exactScale(4),
    zIndex: 10,
    overflow: "hidden",
  },
  badge: {
    fontFamily: "Inter-ExtraBold",
    fontWeight: "800",
    fontSize: moderateScale(11),
  },
  detailsArea: {
    borderBottomLeftRadius: exactScale(12),
    borderBottomRightRadius: exactScale(12),
    paddingHorizontal: exactScale(12),
    paddingTop: exactScale(12),
    flexDirection: "column",
  },
  name: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#111827",
    fontSize: typography.body.fontSize,
    lineHeight: typography.body.lineHeight,
    verticalAlign: "middle",
    letterSpacing: 0,
  },
  description: {
    fontFamily: "Inter-Regular",
    fontWeight: "400",
    fontSize: moderateScale(12),
    lineHeight: moderateScale(18),
    letterSpacing: 0,
    verticalAlign: "middle",
    color: "#6A6A6A",
    marginTop: exactScale(2),
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    columnGap: exactScale(6),
    marginTop: exactScale(6),
    marginBottom: exactScale(8),
  },
  price: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    fontSize: moderateScale(16),
    lineHeight: moderateScale(22.5),
    letterSpacing: 0,
    verticalAlign: "middle",
    color: "#0F172A",
  },
  mrp: {
    fontFamily: "Inter-Regular",
    fontWeight: "400",
    fontSize: moderateScale(12),
    lineHeight: moderateScale(18),
    letterSpacing: 0,
    verticalAlign: "middle",
    textDecorationLine: "line-through",
    color: "#6A6A6A",
  },
  buttonWrap: {
    paddingTop: exactScale(6),
    paddingBottom: exactScale(12),
    alignItems: "center",
  },
  cartBtn: {
    width: exactScale(137),
    height: CART_BUTTON_HEIGHT,
    borderRadius: exactScale(6),
    borderWidth: 1,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: exactScale(8.64),
    paddingRight: exactScale(13.82),
    paddingBottom: exactScale(8.64),
    paddingLeft: exactScale(13.82),
  },
  addBtn: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    fontSize: moderateScale(14),
    lineHeight: moderateScale(16.84),
    letterSpacing: 0,
    verticalAlign: "middle",
  },
  cartBtnActive: {
    width: exactScale(137),
    height: CART_BUTTON_HEIGHT,
    borderRadius: exactScale(6),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: exactScale(4),
  },
  counterBtn: {
    width: exactScale(36),
    height: exactScale(36),
    alignItems: "center",
    justifyContent: "center",
  },
  counter: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    color: "#FFFFFF",
    lineHeight: moderateScale(20),
    fontSize: moderateScale(20),
  },
  counterNumberBox: {
    width: exactScale(24),
    height: exactScale(24),
    alignItems: "center",
    justifyContent: "center",
  },
  counterVal: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#FFFFFF",
    fontSize: moderateScale(14),
    textAlign: "center",
  },
  sectionWrap: {
    paddingTop: exactScale(24),
    paddingBottom: exactScale(32),
  },
  sectionHeaderRow: {
    paddingHorizontal: exactScale(16),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: exactScale(16),
  },
  sectionTitleCol: {
    flex: 1,
    paddingRight: exactScale(8),
  },
  sectionTitle: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#111827",
    fontSize: moderateScale(16),
    lineHeight: moderateScale(20),
    letterSpacing: 0,
    verticalAlign: "middle",
  },
  sectionSubtitle: {
    fontFamily: "Inter-ExtraBold",
    fontWeight: "800",
    fontSize: moderateScale(22),
    lineHeight: moderateScale(30),
    letterSpacing: 0,
    verticalAlign: "middle",
  },
  subtitleUnderline: {
    height: exactScale(3),
    width: exactScale(160),
    marginTop: exactScale(6),
    borderRadius: exactScale(2),
    opacity: 0.6,
  },
  headerImage: {
    width: "25%",
    height: exactScale(75),
  },
  scrollContent: {
    flexDirection: "row",
    paddingLeft: exactScale(20),
    paddingRight: exactScale(40),
  },
});
