import { colors } from "@/src/constants/theme";
import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: exactScale(20),
    paddingBottom: exactScale(8),
  },
  leftContainer: {
    flex: 1,
    minWidth: 0,
    position: "relative",
  },
  deliverLabel: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    textTransform: "uppercase",
    fontSize: moderateScale(12),
    lineHeight: moderateScale(14),
    letterSpacing: 0.4,
    color: "#333232",
  },
  locationTouchable: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: exactScale(4),
    minWidth: 0,
  },
  locationText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    textTransform: "capitalize",
    fontSize: moderateScale(16),
    lineHeight: moderateScale(20),
    letterSpacing: 0,
    color: colors.text,
    maxWidth: exactScale(150),
    flexShrink: 1,
  },
  dropDownIcon: {
    marginLeft: exactScale(10),
    width: exactScale(10),
    height: exactScale(5),
    flexShrink: 0,
  },
  rightContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: exactScale(12),
    flexShrink: 0,
  },
  walletTouchable: {
    alignItems: "center",
  },
  iconBtn: {
    width: exactScale(44),
    height: exactScale(44),
    borderRadius: exactScale(9999),
    backgroundColor: "#FFFFFF",
    shadowColor: "#919EAB",
    shadowOffset: { width: 0, height: exactScale(2) },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  walletIcon: {
    width: exactScale(32),
    height: exactScale(32),
  },
  walletBadgeWrap: {
    minWidth: exactScale(54),
    height: exactScale(19),
    marginTop: -exactScale(14),
    paddingTop: exactScale(2),
    paddingRight: exactScale(9),
    paddingBottom: exactScale(2),
    paddingLeft: exactScale(9),
    borderRadius: exactScale(18),
    borderWidth: 0.5,
    borderColor: "#919EAB33",
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  walletBadgeText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    fontSize: moderateScale(10),
    lineHeight: moderateScale(13),
    letterSpacing: 0,
    color: colors.text,
    padding: 1,
  },
  notificationBtn: {
    width: exactScale(44),
    height: exactScale(44),
    borderRadius: exactScale(9999),
    backgroundColor: "#FFFFFF",
    shadowColor: "#919EAB",
    shadowOffset: { width: 0, height: exactScale(2) },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  notificationIcon: {
    width: exactScale(24),
    height: exactScale(26),
  },
  badge: {
    minWidth: exactScale(18),
    height: exactScale(18),
    position: "absolute",
    top: -exactScale(4),
    right: -exactScale(4),
    backgroundColor: "#C22923",
    borderRadius: exactScale(9999),
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: exactScale(4),
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  badgeText: {
    fontFamily: "Inter-Bold",
    fontWeight: "700",
    color: "#FFFFFF",
    fontSize: moderateScale(10),
    lineHeight: moderateScale(12),
  },
  locationHintArrow: {
    width: exactScale(10),
    height: exactScale(10),
    backgroundColor: "#1A1C1E",
    transform: [{ rotate: "45deg" }],
    marginLeft: exactScale(14),
    marginBottom: -exactScale(7),
    zIndex: 1,
  },
  locationHintBubble: {
    backgroundColor: "#1A1C1E",
    borderRadius: exactScale(10),
    paddingVertical: exactScale(10),
    paddingHorizontal: exactScale(12),
    maxWidth: exactScale(230),
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: exactScale(4) },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
    flexDirection: "row",
    alignItems: "center",
  },
  locationHintText: {
    fontFamily: "Inter-Medium",
    fontWeight: "500",
    fontSize: moderateScale(12),
    lineHeight: moderateScale(16),
    color: "#FFFFFF",
    flexShrink: 1,
  },
});
