export enum NotificationType {
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_PACKED = 'ORDER_PACKED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  RETURN_REQUESTED = 'RETURN_REQUESTED',
  REFUND_INITIATED = 'REFUND_INITIATED',
  REFUND_COMPLETED = 'REFUND_COMPLETED',
  PRESCRIPTION_UPLOADED = 'PRESCRIPTION_UPLOADED',
  PRESCRIPTION_APPROVED = 'PRESCRIPTION_APPROVED',
  PRESCRIPTION_REJECTED = 'PRESCRIPTION_REJECTED',
  PRODUCT = 'PRODUCT',
  PRODUCT_BACK_IN_STOCK = 'PRODUCT_BACK_IN_STOCK',
  PRICE_DROP = 'PRICE_DROP',
  CATEGORY = 'CATEGORY',
  OFFER = 'OFFER',
  COUPON = 'COUPON',
  CART_REMINDER = 'CART_REMINDER',
  WISHLIST = 'WISHLIST',
  MEDICINE_REMINDER = 'MEDICINE_REMINDER',
  LAB_REPORT_READY = 'LAB_REPORT_READY',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  CHAT = 'CHAT',
  WALLET = 'WALLET',
  LOYALTY_POINTS = 'LOYALTY_POINTS',
  PROFILE_VERIFICATION = 'PROFILE_VERIFICATION',
  KYC_REQUIRED = 'KYC_REQUIRED',
  APP_UPDATE = 'APP_UPDATE',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  HOME = 'HOME',
  NOTIFICATIONS = 'NOTIFICATIONS',
}

export interface NotificationPayload {
  type: NotificationType;
  id?: string;
  data?: Record<string, any>;
}
