import { moderateScale, scale, verticalScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#F5F6FB",
  },
  loadingCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: scale(16),
    padding: scale(20),
    width: "100%",
    borderWidth: 1,
    borderColor: "#919EAB33",
  },
  orderSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    paddingBottom: verticalScale(16),
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  bagIconBox: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(20),
    backgroundColor: "#FFF1F1",
    alignItems: "center",
    justifyContent: "center",
    marginRight: scale(12),
  },
  orderNumberText: {
    fontSize: moderateScale(15),
    fontWeight: "700",
    color: "#222222",
  },
  orderMetaText: {
    fontSize: moderateScale(12),
    fontWeight: "400",
    color: "#6A6A6A",
    marginTop: verticalScale(2),
  },
  questionText: {
    fontSize: moderateScale(14),
    fontWeight: "700",
    color: "#222222",
    marginTop: verticalScale(18),
    marginBottom: verticalScale(12),
  },
  reasonsContainer: {
    width: "100%",
  },
  reasonsScrollArea: {
    width: "100%",
    maxHeight: verticalScale(260),
  },
  reasonsScrollContent: {
    width: "100%",
  },
  reasonItemWrap: {
    width: "100%",
  },
  reasonRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: verticalScale(12),
    width: "100%",
  },
  reasonIconBox: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(20),
    alignItems: "center",
    justifyContent: "center",
    marginRight: scale(12),
    overflow: "hidden",
  },
  reasonTextCol: {
    flex: 1,
    marginRight: scale(8),
  },
  reasonLabel: {
    fontSize: moderateScale(14),
    fontWeight: "600",
    color: "#222222",
  },
  reasonDesc: {
    fontSize: moderateScale(12),
    color: "#9CA3AF",
    marginTop: verticalScale(2),
  },
  radioCircle: {
    width: scale(22),
    height: scale(22),
    borderRadius: scale(11),
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  radioCircleSelected: {
    borderColor: "#0F7635",
  },
  radioCircleUnselected: {
    borderColor: "#D1D5DB",
  },
  radioDot: {
    width: scale(12),
    height: scale(12),
    borderRadius: scale(6),
    backgroundColor: "#0F7635",
  },
  otherInput: {
    width: "100%",
    minHeight: verticalScale(80),
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: scale(10),
    paddingHorizontal: scale(14),
    paddingVertical: verticalScale(12),
    fontWeight: "400",
    fontSize: moderateScale(13),
    color: "#1A1C1E",
    textAlignVertical: "top",
    marginTop: verticalScale(12),
    marginBottom: verticalScale(4),
  },
  errorText: {
    width: "100%",
    marginTop: verticalScale(8),
    fontWeight: "400",
    fontSize: moderateScale(12),
    color: "#DC2626",
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: scale(20),
    paddingTop: verticalScale(16),
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  submitBtn: {
    width: "100%",
    paddingVertical: verticalScale(14),
    borderRadius: scale(12),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#D32F2F",
  },
  submitBtnDisabled: {
    opacity: 0.7,
  },
  submitBtnText: {
    fontSize: moderateScale(16),
    fontWeight: "700",
    color: "#fff",
  },
  footerNotice: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: verticalScale(14),
    gap: scale(5),
  },
  footerNoticeText: {
    fontSize: moderateScale(12),
    fontWeight: "400",
    color: "#9CA3AF",
  },
});
