import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#F5F6FB",
  },
  getInvoiceBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: exactScale(4),
  },
  getInvoiceText: {
    fontSize: moderateScale(14),
    fontWeight: "600",
    color: "#0F7635",
  },
  scrollContent: {
    paddingTop: exactScale(12),
    gap: exactScale(10),
  },
  headerStatusWrap: {
    paddingHorizontal: exactScale(16),
    paddingVertical: exactScale(12),
    marginHorizontal: exactScale(16),
  },
  headerStatusLabel: {
    fontSize: moderateScale(13),
    fontWeight: "500",
    color: "#1C2024",
    letterSpacing: 0.5,
  },
  headerStatusDateRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: exactScale(4),
  },
  headerStatusDateText: {
    fontSize: moderateScale(20),
    fontWeight: "700",
    color: "#1C2024",
  },
  headerStatusBadge: {
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: exactScale(8),
    paddingVertical: exactScale(6),
    marginLeft: exactScale(12),
  },
  headerStatusBadgeText: {
    fontSize: moderateScale(11),
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  expectedDeliveryText: {
    fontSize: moderateScale(13),
    fontWeight: "500",
    color: "#60646C",
    marginTop: exactScale(6),
  },
  trackingSectionCard: {
    paddingTop: exactScale(16),
    paddingBottom: exactScale(8),
  },
  trackingSectionTitle: {
    fontSize: moderateScale(14),
    fontWeight: "700",
    color: "#1C2024",
    marginBottom: exactScale(16),
    paddingHorizontal: exactScale(16),
  },
  trackingDivider: {
    borderTopWidth: 1,
    borderColor: "#E5E7EB",
    marginHorizontal: exactScale(10),
    borderStyle: "dashed",
    marginTop: exactScale(4),
  },
  viewAllUpdatesBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: exactScale(12),
  },
  viewAllUpdatesText: {
    fontSize: moderateScale(13),
    fontWeight: "600",
    color: "#0F7635",
    marginRight: exactScale(4),
  },
  billCardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: exactScale(16),
    paddingVertical: exactScale(16),
  },
  billLeftCol: {
    flexDirection: "row",
    alignItems: "center",
    gap: exactScale(12),
  },
  billIconBox: {
    borderWidth: 1,
    borderColor: "#E2E8F0",
    width: exactScale(40),
    height: exactScale(40),
    borderRadius: exactScale(4),
    backgroundColor: "#F8FAFC",
    alignItems: "center",
    justifyContent: "center",
  },
  billTitle: {
    fontSize: moderateScale(14),
    fontWeight: "700",
    color: "#1C2024",
  },
  billSubtitle: {
    fontSize: moderateScale(11),
    fontWeight: "500",
    color: "#60646C",
  },
  billRightCol: {
    flexDirection: "row",
    alignItems: "center",
    gap: exactScale(8),
  },
  billTotalText: {
    fontSize: moderateScale(15),
    fontWeight: "700",
    color: "#1C2024",
  },
  returnToast: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEF9C3",
    borderWidth: 1,
    borderColor: "#FDE047",
    position: "absolute",
    left: exactScale(16),
    right: exactScale(16),
    borderRadius: exactScale(8),
    paddingHorizontal: exactScale(16),
    paddingVertical: exactScale(12),
    zIndex: 99,
    elevation: 5,
  },
  returnToastText: {
    fontSize: moderateScale(13),
    fontWeight: "600",
    color: "#1C2024",
    marginLeft: exactScale(8),
    flex: 1,
  },
  reorderBar: {
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#919EAB33",
    paddingHorizontal: exactScale(16),
    paddingTop: exactScale(12),
  },
  reorderBtn: {
    alignItems: "center",
    backgroundColor: "#0F7635",
    borderRadius: exactScale(8),
    paddingVertical: exactScale(15),
  },
  reorderBtnAddingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: exactScale(8),
  },
  reorderBtnText: {
    fontSize: moderateScale(14),
    fontWeight: "600",
    color: "#FFFFFF",
  },
  stepRow: {
    flexDirection: "row",
    paddingHorizontal: exactScale(16),
  },
  stepLeftCol: {
    width: exactScale(26),
    alignItems: "center",
    alignSelf: "stretch",
  },
  stepDotWrap: {
    height: exactScale(24),
    justifyContent: "center",
    alignItems: "center",
  },
  stepLine: {
    width: exactScale(2),
    flex: 1,
  },
  stepContentCol: {
    flex: 1,
    paddingLeft: exactScale(10),
  },
  stepTitle: {
    fontSize: moderateScale(13),
    fontWeight: "600",
  },
  stepTime: {
    fontSize: moderateScale(13),
    color: "#60646C",
    marginTop: exactScale(2),
  },
  dotCancelled: {
    width: exactScale(18),
    height: exactScale(18),
    borderRadius: exactScale(9),
    backgroundColor: "#DC2626",
    alignItems: "center",
    justifyContent: "center",
  },
  dotCancelledText: {
    color: "#FFFFFF",
    fontSize: moderateScale(9),
    fontWeight: "700",
    lineHeight: moderateScale(11),
  },
  dotActive: {
    width: exactScale(22),
    height: exactScale(22),
    borderRadius: exactScale(11),
    backgroundColor: "#16A34A",
    borderWidth: exactScale(3),
    borderColor: "#DCFCE7",
    alignItems: "center",
    justifyContent: "center",
  },
  dotActiveInner: {
    width: exactScale(8),
    height: exactScale(8),
    borderRadius: exactScale(4),
    backgroundColor: "#FFFFFF",
  },
  dotCompleted: {
    width: exactScale(18),
    height: exactScale(18),
    borderRadius: exactScale(9),
    backgroundColor: "#16A34A",
    alignItems: "center",
    justifyContent: "center",
  },
  dotCompletedText: {
    color: "#FFFFFF",
    fontSize: moderateScale(9),
    fontWeight: "700",
    lineHeight: moderateScale(11),
  },
  dotPending: {
    width: exactScale(16),
    height: exactScale(16),
    borderRadius: exactScale(8),
    borderWidth: exactScale(1.5),
    borderColor: "#D1D5DB",
    backgroundColor: "#FFFFFF",
  },
});
