import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#F5F6FB",
  },
  loadingCenter: {
    flex: 1,
    backgroundColor: "#F5F6FB",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: exactScale(32),
  },
  emptyTitle: {
    fontSize: moderateScale(15),
    fontWeight: "700",
    color: "#222222",
    textAlign: "center",
    marginBottom: exactScale(8),
  },
  emptySubtitle: {
    fontSize: moderateScale(13),
    fontWeight: "500",
    color: "#60646C",
    textAlign: "center",
  },
  existingReturnBtn: {
    backgroundColor: "#0F1724",
    borderRadius: exactScale(8),
    paddingVertical: exactScale(14),
    paddingHorizontal: exactScale(32),
    marginTop: exactScale(24),
  },
  existingReturnBtnText: {
    fontSize: moderateScale(14),
    fontWeight: "700",
    color: "#FFFFFF",
  },
  scrollContent: {
    paddingVertical: exactScale(12),
    gap: exactScale(10),
  },
  benefitRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: exactScale(16),
    paddingVertical: exactScale(12),
    gap: exactScale(12),
  },
  benefitText: {
    fontSize: moderateScale(13),
    fontWeight: "600",
    color: "#1C2024",
  },
  benefitDivider: {
    height: 1,
    backgroundColor: "#919EAB33",
  },
  sectionHeading: {
    fontSize: moderateScale(14),
    fontWeight: "700",
    color: "#222222",
    paddingHorizontal: exactScale(16),
    paddingTop: exactScale(16),
    paddingBottom: exactScale(12),
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: exactScale(16),
    paddingVertical: exactScale(12),
  },
  itemTouch: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  itemImageWrap: {
    width: exactScale(56),
    height: exactScale(56),
    borderRadius: exactScale(4),
    borderWidth: 1,
    borderColor: "#919EAB33",
    backgroundColor: "#FAFAFA",
    alignItems: "center",
    justifyContent: "center",
    marginRight: exactScale(12),
    overflow: "hidden",
  },
  itemImg: {
    width: exactScale(50),
    height: exactScale(50),
  },
  itemNameText: {
    fontSize: moderateScale(13),
    fontWeight: "600",
  },
  itemBrandText: {
    fontSize: moderateScale(13),
    fontWeight: "500",
    marginTop: exactScale(2),
  },
  checkbox: {
    marginLeft: exactScale(8),
    marginTop: exactScale(2),
    width: exactScale(24),
    height: exactScale(24),
    borderRadius: exactScale(4),
    alignItems: "center",
    justifyContent: "center",
    borderWidth: exactScale(1.5),
  },
  checkboxChecked: {
    borderColor: "#0F7635",
    backgroundColor: "#0F7635",
  },
  checkboxUnchecked: {
    borderColor: "#9CA3AF",
    backgroundColor: "transparent",
  },
  checkboxDisabled: {
    borderColor: "#D1D5DB",
    backgroundColor: "#F3F4F6",
  },
  checkMarkText: {
    color: "#FFFFFF",
    fontSize: moderateScale(12),
    fontWeight: "700",
    lineHeight: moderateScale(14),
  },
  nonReturnableBadge: {
    backgroundColor: "#FEF2F2",
    borderColor: "#FECACA",
    borderWidth: 1,
    borderRadius: exactScale(6),
    paddingHorizontal: exactScale(8),
    paddingVertical: exactScale(3),
    alignSelf: "flex-start",
  },
  nonReturnableText: {
    color: "#DC2626",
    fontSize: moderateScale(11),
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  qtySelector: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: exactScale(12),
    paddingVertical: exactScale(4),
    gap: exactScale(12),
    borderWidth: 1,
    borderColor: "#919EAB33",
    borderRadius: exactScale(6),
    alignSelf: "flex-start",
  },
  qtyBtnText: {
    fontSize: moderateScale(16),
    fontWeight: "500",
    lineHeight: moderateScale(16),
  },
  qtyValueText: {
    fontSize: moderateScale(13),
    fontWeight: "700",
    minWidth: exactScale(14),
    textAlign: "center",
  },
  reasonDetailsCard: {
    paddingHorizontal: exactScale(16),
    paddingBottom: exactScale(16),
  },
  reasonDivider: {
    height: 1,
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: "#919EAB33",
    borderStyle: "dashed",
    marginBottom: exactScale(16),
  },
  reasonRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  reasonHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: exactScale(8),
  },
  reasonTitleText: {
    fontSize: moderateScale(14),
    fontWeight: "700",
    color: "#222222",
  },
  reasonDetailsText: {
    fontSize: moderateScale(12),
    fontWeight: "500",
    color: "#60646C",
    marginTop: exactScale(4),
  },
  reasonPhotosRow: {
    flexDirection: "row",
    marginTop: exactScale(12),
    gap: exactScale(8),
  },
  reasonThumb: {
    width: exactScale(52),
    height: exactScale(52),
    borderRadius: exactScale(8),
  },
  reasonEditBtn: {
    marginTop: exactScale(4),
    alignSelf: "flex-end",
    marginBottom: exactScale(2),
  },
  reasonEditText: {
    fontSize: moderateScale(14),
    fontWeight: "700",
    color: "#0F7635",
  },
  itemDashedDivider: {
    borderTopWidth: 1,
    borderColor: "#E5E7EB",
    marginHorizontal: exactScale(10),
    borderStyle: "dashed",
  },
  radioCard: {
    marginHorizontal: exactScale(16),
    borderRadius: exactScale(8),
    borderWidth: exactScale(1.33),
  },
  radioCardSelected: {
    borderColor: "#0F7635",
    backgroundColor: "#F4FBF6",
  },
  radioCardUnselected: {
    borderColor: "#919EAB33",
    backgroundColor: "#FFFFFF",
  },
  radioInnerRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: exactScale(16),
    gap: exactScale(12),
  },
  radioCircle: {
    width: exactScale(20),
    height: exactScale(20),
    borderRadius: exactScale(10),
    borderWidth: exactScale(1.5),
    alignItems: "center",
    justifyContent: "center",
  },
  radioCircleSelected: {
    borderColor: "#0F7635",
  },
  radioCircleUnselected: {
    borderColor: "#919EAB",
  },
  radioDot: {
    width: exactScale(10),
    height: exactScale(10),
    borderRadius: exactScale(5),
    backgroundColor: "#0F7635",
  },
  radioTitle: {
    fontSize: moderateScale(14),
    fontWeight: "700",
  },
  radioTitleSelected: {
    color: "#0F7635",
  },
  radioTitleUnselected: {
    color: "#0F1724",
  },
  radioSubtitle: {
    fontSize: moderateScale(13),
    fontWeight: "500",
    color: "#60646C",
    marginTop: exactScale(2),
  },
  bottomBar: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: exactScale(16),
    borderTopWidth: 1,
    borderTopColor: "#F0F0F0",
    paddingTop: exactScale(16),
  },
  pickupAddressTitle: {
    fontSize: moderateScale(14),
    fontWeight: "700",
    color: "#222222",
    marginBottom: exactScale(4),
  },
  pickupAddressRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: exactScale(16),
  },
  pickupAddressText: {
    fontSize: moderateScale(13),
    fontWeight: "500",
    color: "#60646C",
    lineHeight: moderateScale(20),
    flex: 1,
  },
  changeAddressText: {
    fontSize: moderateScale(13),
    fontWeight: "700",
    color: "#0F7635",
  },
  submitBtn: {
    backgroundColor: "#0F7635",
    borderRadius: exactScale(8),
    paddingVertical: exactScale(16),
    alignItems: "center",
  },
  submitBtnUploadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: exactScale(8),
  },
  submitBtnText: {
    fontSize: moderateScale(15),
    fontWeight: "600",
    color: "#FFFFFF",
  },
});
