import { colors } from "@/src/constants/theme";
import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  cardContainer: {
    marginBottom: exactScale(12),
    position: "relative",
  },
  cardActive: {
    opacity: 1,
  },
  cardInactive: {
    opacity: 0.5,
  },
  cardTouchable: {
    backgroundColor: "#FFFFFF",
    borderRadius: exactScale(13),
    borderWidth: 1,
    borderColor: "#919EAB33",
  },
  cardTop: {
    minHeight: exactScale(67),
    paddingHorizontal: exactScale(16),
    paddingVertical: exactScale(12),
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
    borderTopLeftRadius: exactScale(13),
    borderTopRightRadius: exactScale(13),
  },
  iconWrapper: {
    width: exactScale(40),
    height: exactScale(40),
    borderRadius: exactScale(6),
    borderWidth: 1,
    borderColor: "#919EAB33",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  infoCol: {
    marginLeft: exactScale(12),
    flex: 1,
  },
  discountText: {
    fontSize: moderateScale(17),
    lineHeight: moderateScale(22),
    fontWeight: "700",
    color: "#000000",
  },
  descText: {
    color: "#E53827",
    fontSize: moderateScale(13),
    lineHeight: moderateScale(17),
    fontWeight: "500",
    marginTop: exactScale(2),
  },
  expiryText: {
    fontSize: moderateScale(11),
    lineHeight: moderateScale(15),
    fontWeight: "500",
    color: "#6A6A6A",
    marginTop: exactScale(3),
  },
  fadedIconContainer: {
    position: "absolute",
    right: exactScale(-15),
    top: exactScale(-10),
    zIndex: -1,
  },
  dashedDivider: {
    height: 1,
    marginHorizontal: exactScale(10),
    borderWidth: 1,
    borderColor: "#919EAB33",
    borderStyle: "dashed",
    borderRadius: 1,
  },
  cardBottom: {
    height: exactScale(46),
    paddingHorizontal: exactScale(16),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#ffffff",
    borderBottomLeftRadius: exactScale(13),
    borderBottomRightRadius: exactScale(13),
  },
  couponCodeText: {
    flexShrink: 1,
    marginRight: exactScale(8),
    fontSize: moderateScale(14),
    fontWeight: "700",
    color: "#000000",
    letterSpacing: 0.5,
  },
  applyBtn: {
    minWidth: exactScale(55),
    paddingHorizontal: exactScale(8),
    height: exactScale(28),
    borderRadius: exactScale(4),
    alignItems: "center",
    justifyContent: "center",
  },
  applyBtnActive: {
    backgroundColor: colors.primary,
    borderWidth: 0,
  },
  applyBtnInactive: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E4E7EC",
  },
  applyBtnText: {
    fontSize: moderateScale(13),
    lineHeight: moderateScale(17),
    fontWeight: "700",
  },
  applyBtnTextActive: {
    color: "#FFFFFF",
  },
  applyBtnTextInactive: {
    color: "#9CA3AF",
  },
  leftNotchWrapper: {
    position: "absolute",
    left: 0,
    bottom: exactScale(36),
    width: exactScale(10),
    height: exactScale(20),
    overflow: "hidden",
    zIndex: 10,
  },
  leftNotchCircle: {
    width: exactScale(20),
    height: exactScale(20),
    borderRadius: exactScale(10),
    backgroundColor: "#F5F6FB",
    borderWidth: 1,
    borderColor: "#919EAB33",
    position: "absolute",
    left: exactScale(-10),
    top: 0,
  },
  rightNotchWrapper: {
    position: "absolute",
    right: 0,
    bottom: exactScale(36),
    width: exactScale(10),
    height: exactScale(20),
    overflow: "hidden",
    zIndex: 10,
  },
  rightNotchCircle: {
    width: exactScale(20),
    height: exactScale(20),
    borderRadius: exactScale(10),
    backgroundColor: "#F5F6FB",
    borderWidth: 1,
    borderColor: "#919EAB33",
    position: "absolute",
    right: exactScale(-10),
    top: 0,
  },
});
