import { colors } from "@/src/theme";
import { moderateScale, scale, verticalScale } from "@/src/utils/exactScale";
import { Platform, StyleSheet } from "react-native";

const FIELD_ERROR = "#EF4444";

export const styles = StyleSheet.create({
  boxRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    marginVertical: verticalScale(10),
    marginHorizontal: scale(2),
    width: "100%",
    alignSelf: "center",
  },
  otpBox: {
    flex: 1,
    maxWidth: 48,
    aspectRatio: 1,
    borderRadius: scale(10),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  boxBorderThin: { borderWidth: 1 },
  boxBorderThick: { borderWidth: 2 },
  boxIdle: { borderColor: "#D0D5DD" },
  boxAccent: { borderColor: colors.primary },
  boxError: { borderColor: FIELD_ERROR },
  boxFillActive: { backgroundColor: "#F0FDF4" },
  boxFillPlain: { backgroundColor: colors.white },
  otpDigit: {
    textAlignVertical: "center",
    includeFontPadding: false,
    fontSize: moderateScale(24),
    fontFamily: Platform.OS === "android" ? "Inter_700Bold" : undefined,
    fontWeight: "700",
    lineHeight: Platform.OS === "android" ? verticalScale(24) : undefined,
    letterSpacing: 0,
    color: "#111827",
    textAlign: "center",
  },
  caret: {
    width: 2,
    height: verticalScale(24),
    borderRadius: 1,
    backgroundColor: "#0F7635",
  },
  hiddenInput: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 1,
    height: 1,
    opacity: 0,
    color: "transparent",
    padding: 0,
  },
  error: {
    fontSize: moderateScale(13),
    fontWeight: "500",
    color: FIELD_ERROR,
    textAlign: "center",
    marginBottom: verticalScale(8),
  },
  btnEnabled: { opacity: 1 },
  btnDisabled: { opacity: 0.6 },
  resendText: {
    fontSize: moderateScale(13),
    fontWeight: "500",
    color: "#637381",
    paddingVertical: verticalScale(4),
  },
  resendHighlight: { color: "#0F7635", fontWeight: "700" },
  resendBtn: {
    fontSize: moderateScale(13),
    fontWeight: "700",
    color: "#0F7635",
    lineHeight: moderateScale(15),
  },
  resendUnderline: {
    borderBottomWidth: 1,
    borderBottomColor: "#0F7635",
    paddingBottom: verticalScale(1),
  },
  btn: {
    width: "100%",
    maxWidth: scale(361),
    alignSelf: "center",
    minHeight: verticalScale(50),
    borderRadius: scale(12),
    paddingTop: verticalScale(10),
    paddingRight: scale(16),
    paddingBottom: verticalScale(10),
    paddingLeft: scale(16),
    gap: scale(12),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    marginBottom: verticalScale(8),
  },
  btnText: {
    fontSize: moderateScale(16),
    fontWeight: "700",
    color: "white",
    marginRight: scale(8),
  },
});
