import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  corporateBadge: {
    paddingLeft: exactScale(18),
    paddingRight: exactScale(12),
    paddingVertical: exactScale(5.5),
    justifyContent: "center",
    alignItems: "center",
  },
  corporateBadgeText: {
    fontSize: moderateScale(11),
    letterSpacing: 0.4,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  statusBadgeWrap: {
    borderRadius: exactScale(6),
    paddingHorizontal: exactScale(10),
    paddingVertical: exactScale(5),
    borderWidth: 1,
    position: "absolute",
    top: exactScale(16),
    right: exactScale(16),
    zIndex: 10,
  },
  statusBadgeText: {
    fontSize: moderateScale(11),
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: exactScale(14),
    borderWidth: 1,
    borderColor: "#E3E6E8",
    marginHorizontal: exactScale(16),
    marginBottom: exactScale(20),
    overflow: "hidden",
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: exactScale(16),
    paddingTop: exactScale(16),
    paddingBottom: exactScale(10),
  },
  metaColsWrap: {
    flexDirection: "row",
    gap: exactScale(20),
    paddingRight: exactScale(110),
  },
  metaLabel: {
    fontSize: moderateScale(10),
    fontWeight: "600",
    color: "#6A6A6A",
    letterSpacing: 0.6,
  },
  metaValue: {
    fontSize: moderateScale(13),
    fontWeight: "700",
    color: "#222222",
    marginTop: exactScale(3),
  },
  itemsCountText: {
    fontSize: moderateScale(10),
    fontWeight: "600",
    color: "#6A6A6A",
    letterSpacing: 0.6,
    paddingHorizontal: exactScale(16),
    marginBottom: exactScale(10),
  },
  thumbsWrap: {
    flexDirection: "row",
    paddingHorizontal: exactScale(16),
    gap: exactScale(12),
    marginBottom: exactScale(12),
  },
  thumbBox: {
    flex: 1,
    aspectRatio: 1,
    maxWidth: exactScale(62),
    borderRadius: exactScale(8),
    borderWidth: 1,
    borderColor: "#EEEFF1",
    backgroundColor: "#FAFAFA",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  thumbExtraBox: {
    flex: 1,
    aspectRatio: 1,
    maxWidth: exactScale(62),
    borderRadius: exactScale(8),
    borderWidth: 1,
    borderColor: "#EEEFF1",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  thumbExtraText: {
    fontSize: moderateScale(18),
    fontWeight: "600",
    color: "#222222",
  },
  deliveryCorporateRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingHorizontal: exactScale(16),
    paddingBottom: exactScale(14),
  },
  dividerHorizontal: {
    height: 1,
    backgroundColor: "#919EAB33",
  },
  dividerVertical: {
    width: 1,
    backgroundColor: "#919EAB33",
  },
  actionsRow: {
    flexDirection: "row",
  },
  actionBtn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: exactScale(14),
  },
  actionBtnText: {
    fontSize: moderateScale(14),
    fontWeight: "700",
    color: "#0F7635",
  },
  addingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: exactScale(6),
  },
  addingText: {
    fontSize: moderateScale(13),
    fontWeight: "600",
    color: "#0F7635",
  },
});
