import { exactScale, moderateScale } from "@/src/utils/exactScale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: "#FFFFFF",
    marginBottom: exactScale(16),
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#DFE3E8",
    borderRadius: exactScale(12),
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: exactScale(10),
    paddingTop: exactScale(12),
    paddingBottom: exactScale(4),
  },
  statusBadge: {
    borderRadius: exactScale(5),
    paddingHorizontal: exactScale(10),
    paddingVertical: exactScale(4),
  },
  statusText: {
    fontSize: moderateScale(11),
    fontWeight: "600",
  },
  menuBtn: {
    padding: exactScale(4),
  },
  rxTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: exactScale(10),
    paddingTop: exactScale(4),
    paddingBottom: exactScale(12),
  },
  rxIconBox: {
    width: exactScale(40),
    height: exactScale(40),
    alignItems: "center",
    justifyContent: "center",
    marginRight: exactScale(12),
    backgroundColor: "#E8F6ED",
    borderRadius: exactScale(10),
  },
  rxDetailsList: {
    paddingHorizontal: exactScale(10),
    paddingBottom: exactScale(16),
    gap: exactScale(16),
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  detailText: {
    fontFamily: "Inter",
    fontSize: moderateScale(13),
    fontWeight: "500",
    color: "#6A6A6A",
    marginLeft: exactScale(10),
  },
  rejectionWrap: {
    paddingHorizontal: exactScale(10),
    paddingBottom: exactScale(16),
  },
  rejectionHeading: {
    fontFamily: "Inter",
    fontWeight: "700",
    color: "#C22307",
    fontSize: moderateScale(13),
    letterSpacing: 0.3,
  },
  rejectionBody: {
    fontFamily: "Inter",
    fontWeight: "500",
    color: "#222222",
    marginTop: exactScale(6),
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
  },
  viewMoreText: {
    fontFamily: "Inter",
    fontWeight: "600",
    color: "#C22307",
    marginTop: exactScale(6),
    fontSize: moderateScale(12),
  },
  divider: {
    height: 1,
    backgroundColor: "#E1E5E8",
    marginHorizontal: exactScale(10),
  },
  footerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: exactScale(10),
    paddingVertical: exactScale(14),
  },
  enableReminderRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  enableReminderText: {
    fontSize: moderateScale(14),
    fontFamily: "Inter",
    fontWeight: "600",
    color: "#222222",
    marginLeft: exactScale(10),
  },
  reorderBtn: {
    backgroundColor: "#0F7635",
    paddingHorizontal: exactScale(20),
    paddingVertical: exactScale(10),
    borderRadius: exactScale(10),
  },
  reorderBtnText: {
    fontSize: moderateScale(13),
    fontFamily: "Inter",
    fontWeight: "600",
    color: "#FFFFFF",
  },
  toggleTrack: {
    width: exactScale(40),
    height: exactScale(22),
    borderRadius: exactScale(11),
    justifyContent: "center",
    padding: exactScale(2),
  },
  toggleThumb: {
    width: exactScale(18),
    height: exactScale(18),
    borderRadius: exactScale(9),
    backgroundColor: "#FFFFFF",
    shadowColor: "#919EAB33",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: exactScale(16),
    paddingVertical: exactScale(12),
  },
  optionText: {
    fontSize: moderateScale(14),
    fontWeight: "500",
    color: "#222222",
    marginLeft: exactScale(12),
  },
  popover: {
    position: "absolute",
    top: exactScale(48),
    right: exactScale(8),
    width: exactScale(210),
    backgroundColor: "#FFFFFF",
    borderRadius: exactScale(16),
    borderWidth: 1,
    borderColor: "#919EAB33",
    zIndex: 10,
  },
});
