import { Platform, StyleSheet } from "react-native";
import { exactScale } from "@/src/utils/exactScale";

export const styles = StyleSheet.create({
  inputWrap: {
    width: "100%",
    maxWidth: exactScale(361),
    alignSelf: "center",
    height: exactScale(56),
    borderRadius: exactScale(8),
    borderWidth: 1,
    paddingTop: exactScale(10),
    paddingRight: exactScale(16),
    paddingBottom: exactScale(10),
    paddingLeft: exactScale(16),
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    gap: exactScale(10),
    marginTop: exactScale(14),
  },
  prefix: {
    fontSize: exactScale(17),
    fontWeight: "500",
    color: "#222222",
  },
  input: {
    flex: 1,
    height: "100%",
    paddingVertical: 0,
    paddingHorizontal: 0,
    fontSize: exactScale(15),
    fontFamily: Platform.OS === "android" ? "Inter_500Medium" : undefined,
    fontWeight: Platform.OS === "android" ? "normal" : "500",
    letterSpacing: 0,
    color: "#222222",
  },
  divider: {
    width: 2,
    height: exactScale(20),
    backgroundColor: "#222222",
  },
  error: {
    fontSize: exactScale(13),
    fontWeight: "500",
    color: "#EF4444",
    marginTop: 6,
    marginBottom: 4,
    paddingHorizontal: 4,
  },
  btn: {
    width: "100%",
    maxWidth: exactScale(361),
    alignSelf: "center",
    height: exactScale(50),
    borderRadius: exactScale(12),
    paddingTop: exactScale(10),
    paddingRight: exactScale(16),
    paddingBottom: exactScale(10),
    paddingLeft: exactScale(16),
    gap: exactScale(12),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0F7635",
    marginVertical: exactScale(16),
  },
  btnText: {
    fontSize: exactScale(16),
    fontWeight: "700",
    color: "white",
    marginRight: 8,
  },
  arrow: { width: exactScale(13), height: exactScale(13) },
});
