import { Platform, StyleSheet } from "react-native";
import { moderateScale, scale } from "react-native-size-matters";

export const styles = StyleSheet.create({
  inputWrap: {
    width: "100%",
    maxWidth: moderateScale(361, 0.3),
    alignSelf: "center",
    height: moderateScale(56, 0.3),
    borderRadius: moderateScale(8, 0.3),
    borderWidth: 1,
    paddingTop: moderateScale(10, 0.3),
    paddingRight: moderateScale(16, 0.3),
    paddingBottom: moderateScale(10, 0.3),
    paddingLeft: moderateScale(16, 0.3),
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    gap: moderateScale(10, 0.3),
    marginTop: moderateScale(14, 0.3),
  },
  prefix: {
    fontSize: moderateScale(17, 0.1),
    fontWeight: "500",
    color: "#222222",
  },
  input: {
    flex: 1,
    height: "100%",
    paddingVertical: 0,
    paddingHorizontal: 0,
    fontSize: moderateScale(15, 0.1),
    fontFamily: Platform.OS === "android" ? "Inter_500Medium" : undefined,
    fontWeight: Platform.OS === "android" ? "normal" : "500",
    letterSpacing: 0,
    color: "#222222",
  },
  divider: {
    width: 2,
    height: moderateScale(20, 0.3),
    backgroundColor: "#222222",
  },
  error: {
    fontSize: moderateScale(13, 0.1),
    fontWeight: "500",
    color: "#EF4444",
    marginTop: 6,
    marginBottom: 4,
    paddingHorizontal: 4,
  },
  btn: {
    width: "100%",
    maxWidth: moderateScale(361, 0.3),
    alignSelf: "center",
    height: moderateScale(50, 0.3),
    borderRadius: moderateScale(12, 0.3),
    paddingTop: moderateScale(10, 0.3),
    paddingRight: moderateScale(16, 0.3),
    paddingBottom: moderateScale(10, 0.3),
    paddingLeft: moderateScale(16, 0.3),
    gap: moderateScale(12, 0.3),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0F7635",
    marginVertical: moderateScale(16, 0.3),
  },
  btnText: {
    fontSize: moderateScale(16, 0.1),
    fontWeight: "700",
    color: "white",
    marginRight: 8,
  },
  arrow: { width: scale(13), height: scale(13) },
});
