import { Platform, StyleSheet } from "react-native";
import { exactScale } from "@/src/utils/exactScale";

export const styles = StyleSheet.create({
  boxRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: exactScale(8),
    marginVertical: exactScale(12),
    marginHorizontal: exactScale(2),
    width: "100%",
    alignSelf: "center",
  },
  otpBox: {
    width: exactScale(48),
    height: exactScale(48),
    borderRadius: exactScale(10),
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  otpInput: {
    padding: 0,
    textAlignVertical: "center",
    includeFontPadding: false,
    fontSize: exactScale(24),
    fontFamily: Platform.OS === "android" ? "Inter_700Bold" : undefined,
    fontWeight: Platform.OS === "android" ? "normal" : "700",
    lineHeight: exactScale(24),
    letterSpacing: 0,
    color: "#111827",
    textAlign: "center",
    width: "100%",
    height: "100%",
  },
  error: {
    fontSize: exactScale(13),
    fontWeight: "500",
    color: "#EF4444",
    textAlign: "center",
    marginBottom: 8,
  },
  resendText: {
    fontSize: exactScale(13),
    fontWeight: "500",
    color: "#637381",
    paddingVertical: 8,
  },
  resendHighlight: { color: "#0F7635", fontWeight: "700" },
  resendBtn: {
    fontSize: exactScale(13),
    fontWeight: "700",
    color: "#0F7635",
    textDecorationLine: "underline",
  },
  btn: {
    width: "100%",
    maxWidth: exactScale(361),
    alignSelf: "center",
    height: exactScale(50),
    borderRadius: exactScale(12),
    paddingTop: exactScale(10),
    paddingRight: exactScale(16),
    paddingBottom: exactScale(10),
    paddingLeft: exactScale(16),
    gap: exactScale(12),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0F7635",
    marginVertical: exactScale(12),
  },
  btnText: {
    fontSize: exactScale(16),
    fontWeight: "700",
    color: "white",
    marginRight: 8,
  },
  arrow: { width: exactScale(13), height: exactScale(13) },
});
