import { Platform, StyleSheet } from "react-native";
import { scale, verticalScale, moderateScale } from "@/src/utils/exactScale";

export const styles = StyleSheet.create({
  boxRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: scale(8),
    marginVertical: verticalScale(12),
    marginHorizontal: scale(2),
    width: "100%",
    alignSelf: "center",
  },
  otpBox: {
    width: scale(48),
    height: scale(48),
    borderRadius: scale(10),
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  otpInput: {
    padding: 0,
    textAlignVertical: "center",
    includeFontPadding: false,
    fontSize: moderateScale(24, 0.3),
    fontFamily: Platform.OS === "android" ? "Inter_700Bold" : undefined,
    fontWeight: Platform.OS === "android" ? "normal" : "700",
    lineHeight: verticalScale(24),
    letterSpacing: 0,
    color: "#111827",
    textAlign: "center",
    width: "100%",
    height: "100%",
  },
  error: {
    fontSize: moderateScale(13, 0.3),
    fontWeight: "500",
    color: "#EF4444",
    textAlign: "center",
    marginBottom: verticalScale(8),
  },
  resendText: {
    fontSize: moderateScale(13, 0.3),
    fontWeight: "500",
    color: "#637381",
    paddingVertical: verticalScale(8),
  },
  resendHighlight: { color: "#0F7635", fontWeight: "700" },
  resendBtn: {
    fontSize: moderateScale(13, 0.3),
    fontWeight: "700",
    color: "#0F7635",
    textDecorationLine: "underline",
  },
  btn: {
    width: "100%",
    maxWidth: scale(361),
    alignSelf: "center",
    minHeight: verticalScale(50),
    borderRadius: scale(12),
    paddingTop: verticalScale(10),
    paddingRight: scale(16),
    paddingBottom: verticalScale(10),
    paddingLeft: scale(16),
    gap: scale(12),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0F7635",
    marginVertical: verticalScale(12),
  },
  btnText: {
    fontSize: moderateScale(16, 0.3),
    fontWeight: "700",
    color: "white",
    marginRight: scale(8),
  },
  arrow: { width: moderateScale(13, 0.3), height: moderateScale(13, 0.3) },
});
