import { Platform, StyleSheet } from "react-native";
import { moderateScale, scale } from "react-native-size-matters";

export const styles = StyleSheet.create({
  boxRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: moderateScale(8, 0.3),
    marginVertical: moderateScale(12, 0.3),
    marginHorizontal: moderateScale(2, 0.3),
    width: "100%",
    alignSelf: "center",
  },
  otpBox: {
    width: moderateScale(48, 0.3),
    height: moderateScale(48, 0.3),
    borderRadius: moderateScale(10, 0.3),
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  otpInput: {
    padding: 0,
    textAlignVertical: "center",
    includeFontPadding: false,
    fontSize: moderateScale(24, 0.1),
    fontFamily: Platform.OS === "android" ? "Inter_700Bold" : undefined,
    fontWeight: Platform.OS === "android" ? "normal" : "700",
    lineHeight: moderateScale(24, 0.1),
    letterSpacing: 0,
    color: "#111827",
    textAlign: "center",
    width: "100%",
    height: "100%",
  },
  error: {
    fontSize: moderateScale(13, 0.1),
    fontWeight: "500",
    color: "#EF4444",
    textAlign: "center",
    marginBottom: 8,
  },
  resendText: {
    fontSize: moderateScale(13, 0.1),
    fontWeight: "500",
    color: "#637381",
    paddingVertical: 8,
  },
  resendHighlight: { color: "#0F7635", fontWeight: "700" },
  resendBtn: {
    fontSize: moderateScale(13, 0.1),
    fontWeight: "700",
    color: "#0F7635",
    textDecorationLine: "underline",
  },
  btn: {
    width: "100%",
    maxWidth: moderateScale(361, 0.3),
    alignSelf: "center",
    height: moderateScale(50, 0.3),
    borderRadius: moderateScale(12, 0.3),
    paddingTop: moderateScale(10, 0.3),
    paddingRight: moderateScale(16, 0.3),
    paddingBottom: moderateScale(10, 0.3),
    paddingLeft: moderateScale(16, 0.3),
    gap: moderateScale(12, 0.3),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0F7635",
    marginVertical: moderateScale(12, 0.3),
  },
  btnText: {
    fontSize: moderateScale(16, 0.1),
    fontWeight: "700",
    color: "white",
    marginRight: 8,
  },
  arrow: { width: scale(13), height: scale(13) },
});
